'use client'
import { useCallback, useEffect, useMemo, useState } from 'react'
import type { Category, Transaction } from '../budgetPageTypes'
import { getEffectiveTransactionScope } from '../transactionScope'
import { supabase } from '../supabaseClient'
import { buildBudgetLimitAlertStates } from './alerts'
import { calculateBudgetLimitUsage } from './calculations'
import { getBudgetLimitScopeDecision } from './scopes'
import { parseGrosze } from '../recurring-payments/money'
import type { BudgetLimitAlertRule, BudgetLimitCategoryNode, BudgetLimitPeriodInstance, BudgetLimitScope, BudgetLimitTransactionCandidate } from './types'
import type { BudgetLimitAlertRow, BudgetLimitPeriodRow, BudgetLimitPlanDraft, BudgetLimitPlanRow, BudgetLimitVersionRow } from './data'

type Params={profileId:string;selectedMonth:string;categoriesById:Record<string,Category>;expenseLevel1Id:string|null;transactions:Transaction[];budgetStartDate?:string|null;getSignedAmountForTransaction:(transaction:Transaction)=>number;enabled?:boolean}
const getRoot=(categoryId:string,categories:Record<string,Category>)=>{let current=categories[categoryId];while(current?.parent_id)current=categories[current.parent_id];return current?.id||null}
const rulesFor=(version:BudgetLimitVersionRow):BudgetLimitAlertRule[]=>[...version.alert_thresholds.map(value=>({id:`threshold-${value}`,kind:'threshold_reached' as const,thresholdPercent:value,enabled:true})),{id:'exceeded',kind:'limit_exceeded',thresholdPercent:100,enabled:true},{id:'forecast',kind:'projected_exceeded',enabled:version.forecast_alert_enabled}]

export function useBudgetLimitsData({profileId,selectedMonth,categoriesById,expenseLevel1Id,transactions,budgetStartDate,getSignedAmountForTransaction,enabled=true}:Params){
 const [plans,setPlans]=useState<BudgetLimitPlanRow[]>([]);const [versions,setVersions]=useState<BudgetLimitVersionRow[]>([]);const [periods,setPeriods]=useState<BudgetLimitPeriodRow[]>([]);const [storedAlerts,setStoredAlerts]=useState<BudgetLimitAlertRow[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{if(!enabled||!profileId)return;setLoading(true);setError(null);const p=await supabase.from('budget_limit_plans').select('*').eq('profile_id',profileId).order('created_at');if(p.error){setLoading(false);setError(p.error.message||'Błąd pobierania limitów');return}const planRows=((p.data||[]) as Array<Omit<BudgetLimitPlanRow,'status'>&{status:string}>).map(plan=>({...plan,status:plan.status==='active'?'active':'inactive'})) as BudgetLimitPlanRow[];const ensured=await Promise.all(planRows.map(plan=>supabase.rpc('ensure_budget_limit_period_v1',{p_plan_id:plan.id,p_month:selectedMonth})));const ensureError=ensured.find(result=>result.error)?.error;if(ensureError){console.error('[budget-limits] Nie udało się zapewnić okresu dla wybranego miesiąca.',ensureError)}const [v,periodResult,alertResult]=await Promise.all([supabase.from('budget_limit_versions').select('*').eq('profile_id',profileId).order('effective_from'),supabase.from('budget_limit_periods').select('*').eq('profile_id',profileId).order('period_start',{ascending:false}),supabase.from('budget_limit_alerts').select('*').eq('profile_id',profileId).order('triggered_at',{ascending:false})]);setLoading(false);if(v.error||periodResult.error){setError((v.error||periodResult.error)?.message||'Błąd pobierania okresów');return}setPlans(planRows);setVersions((v.data||[]) as BudgetLimitVersionRow[]);setPeriods((periodResult.data||[]) as BudgetLimitPeriodRow[]);setStoredAlerts(alertResult.error?[]:(alertResult.data||[]) as BudgetLimitAlertRow[]);if(alertResult.error)console.error('[budget-limits] Nie udało się pobrać alertów limitów.',alertResult.error)},[enabled,profileId,selectedMonth])
 useEffect(()=>{const task=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(task)},[load])
 const categories=useMemo(()=>Object.fromEntries(Object.values(categoriesById).filter(c=>c.level>=1&&c.level<=3).map(c=>[c.id,{id:c.id,level:c.level as 1|2|3,parentId:c.parent_id}])) as Record<string,BudgetLimitCategoryNode>,[categoriesById])
 const candidates=useMemo(()=>getEffectiveTransactionScope(transactions,{mode:'limits',budgetStartDate}).map(transaction=>{const signed=getSignedAmountForTransaction(transaction);return{id:transaction.id,categoryId:transaction.category_id,amountGrosze:parseGrosze(Math.abs(signed).toFixed(2)),rootType:getRoot(transaction.category_id,categoriesById)===expenseLevel1Id?'expense':'income',date:transaction.date,dateKind:transaction.day_is_null?'month_only':'exact_day',isDeleted:transaction.is_deleted,semanticType:'standard'} satisfies BudgetLimitTransactionCandidate}),[budgetStartDate,categoriesById,expenseLevel1Id,getSignedAmountForTransaction,transactions])
 const calculated=useMemo(()=>periods.flatMap(period=>{const version=versions.find(item=>item.id===period.version_id);if(!version)return[];const scope:BudgetLimitScope=version.scope_type==='global_expenses'?{type:'global_expenses'}:version.scope_type==='category_group'?{type:'category_group',categoryIds:version.category_ids}:{type:version.scope_type,categoryId:version.category_id||''};const instance:BudgetLimitPeriodInstance={id:period.id,planId:period.plan_id,versionId:period.version_id,profileId:period.profile_id,periodType:'monthly',periodStart:period.period_start,periodEnd:period.period_end,status:period.status};const summary=calculateBudgetLimitUsage({planId:period.plan_id,period:instance,limitAmountGrosze:parseGrosze(period.limit_amount_snapshot),scope,alertRules:rulesFor(version),transactions:candidates,categoriesById:categories,asOfDate:new Date().toISOString().slice(0,10)});const includedTransactions=transactions.filter(transaction=>{const candidate=candidates.find(item=>item.id===transaction.id);return candidate&&getBudgetLimitScopeDecision({transaction:candidate,scope,categoriesById:categories}).result==='included'&&transaction.date.slice(0,7)===period.period_start.slice(0,7)});return[{period,version,summary,includedTransactions}]}) ,[candidates,categories,periods,transactions,versions])
 const alerts=useMemo(()=>calculated.flatMap(item=>{const plan=plans.find(value=>value.id===item.period.plan_id);if(plan?.status!=='active'||!item.period.is_active_snapshot)return[];const generated=buildBudgetLimitAlertStates({summary:item.summary,rules:rulesFor(item.version),triggeredAt:new Date().toISOString()});return generated.map(alert=>{const threshold=alert.thresholdPercent??0;const stored=storedAlerts.find(row=>row.period_id===alert.periodId&&row.kind===alert.kind&&row.threshold_percent===threshold);return stored||{id:alert.id,profile_id:profileId,plan_id:alert.planId,period_id:alert.periodId,kind:alert.kind,threshold_percent:threshold,spent_at_trigger:alert.spentGroszeAtTrigger/100,limit_at_trigger:alert.limitGroszeAtTrigger/100,triggered_at:alert.triggeredAt,read_at:null,muted_for_period:false,resolved_at:null}})}),[calculated,plans,profileId,storedAlerts])
 const savePlan=useCallback(async(draft:BudgetLimitPlanDraft)=>{const{data:planId,error:saveError}=await supabase.rpc('save_budget_limit_plan_v1',{p_plan_id:draft.id||null,p_name:draft.name,p_scope_type:draft.scope_type,p_category_id:draft.scope_type==='global_expenses'?null:draft.category_id,p_limit_amount:draft.limit_amount,p_effective_month:draft.effective_month,p_alert_thresholds:draft.alert_thresholds,p_forecast_enabled:draft.forecast_alert_enabled,p_status:draft.status});if(saveError)throw new Error(saveError.message);const{error:periodError}=await supabase.rpc('ensure_budget_limit_period_v1',{p_plan_id:planId,p_month:selectedMonth});if(periodError)throw new Error(periodError.message);await load()},[load,selectedMonth])
 const setPlanActive=useCallback(async(id:string,isActive:boolean,effectiveMonth:string,limitAmount?:number)=>{const{error:statusError}=await supabase.rpc('set_budget_limit_plan_active_v1',{p_plan_id:id,p_active:isActive,p_effective_month:effectiveMonth,p_limit_amount:limitAmount??null});if(statusError)throw statusError;await load()},[load])
 const persistAlert=useCallback(async(alert:BudgetLimitAlertRow,mode:'read'|'muted')=>{const payload={...alert,id:alert.id.includes(':')?undefined:alert.id,profile_id:profileId,read_at:mode==='read'?new Date().toISOString():alert.read_at,muted_for_period:mode==='muted'?true:alert.muted_for_period};const{error:alertError}=await supabase.from('budget_limit_alerts').upsert(payload,{onConflict:'period_id,kind,threshold_percent'});if(alertError)throw alertError;await load()},[load,profileId])
 return{plans,versions,periods,alerts,calculated,loading,error,load,createPlan:savePlan,updatePlan:savePlan,setPlanActive,markAlertRead:(alert:BudgetLimitAlertRow)=>persistAlert(alert,'read'),muteAlert:(alert:BudgetLimitAlertRow)=>persistAlert(alert,'muted')}
}
