import type { Category, Transaction } from '../budgetPageTypes'
import type { BudgetLimitUsageSummary } from './types'
import type { BudgetLimitAlertRow, BudgetLimitPeriodRow, BudgetLimitPlanDraft, BudgetLimitPlanRow, BudgetLimitVersionRow } from './data'
import { formatGrosze } from '../recurring-payments/money'

export type BudgetLimitAlertViewModel={id:string;kind:BudgetLimitAlertRow['kind'];label:string;status:'unread'|'read'|'muted';thresholdPercent:number|null;periodId:string;raw:BudgetLimitAlertRow}
export type BudgetLimitCardViewModel={id:string;name:string;scopeLabel:string;limitLabel:string;spentLabel:string;remainingLabel:string;usagePercent:number;usageBarPercent:number;status:BudgetLimitUsageSummary['usageStatus'];forecastLabel:string;periodLabel:string;archived:boolean}
export type BudgetLimitHistoryViewModel={periodId:string;month:string;limitLabel:string;spentLabel:string;remainingLabel:string;usagePercent:number;status:BudgetLimitUsageSummary['usageStatus'];alerts:BudgetLimitAlertViewModel[]}
export type BudgetLimitDetailsViewModel={card:BudgetLimitCardViewModel;transactions:Transaction[];history:BudgetLimitHistoryViewModel[];alerts:BudgetLimitAlertViewModel[];thresholds:number[];summary:BudgetLimitUsageSummary}
export type BudgetLimitCreatorViewModel={title:string;submitLabel:string;draft:BudgetLimitPlanDraft}

const scopeLabel=(version:BudgetLimitVersionRow,categories:Record<string,Category>)=>version.scope_type==='global_expenses'?'Wszystkie wydatki':`${version.scope_type==='category_l2'?'L2':'L3'} · ${version.category_id?categories[version.category_id]?.name||'Kategoria niedostępna':''}`
export const buildBudgetLimitAlertViewModel=(alert:BudgetLimitAlertRow):BudgetLimitAlertViewModel=>({id:alert.id,kind:alert.kind,label:alert.kind==='limit_exceeded'?'Przekroczono 100%':alert.kind==='projected_exceeded'?'Prognozowane przekroczenie':`Przekroczono ${alert.threshold_percent}%`,status:alert.muted_for_period?'muted':alert.read_at?'read':'unread',thresholdPercent:alert.threshold_percent,periodId:alert.period_id,raw:alert})
export const buildBudgetLimitCardViewModel=(plan:BudgetLimitPlanRow,version:BudgetLimitVersionRow,period:BudgetLimitPeriodRow,summary:BudgetLimitUsageSummary,categories:Record<string,Category>):BudgetLimitCardViewModel=>({id:plan.id,name:plan.name,scopeLabel:scopeLabel(version,categories),limitLabel:formatGrosze(summary.limitAmountGrosze),spentLabel:formatGrosze(summary.spentAmountGrosze),remainingLabel:formatGrosze(summary.remainingAmountGrosze),usagePercent:summary.usagePercent,usageBarPercent:Math.min(Math.max(summary.usagePercent,0),100),status:summary.usageStatus,forecastLabel:summary.projectedSpendGrosze===null?'Brak prognozy':`Prognoza: ${formatGrosze(summary.projectedSpendGrosze)}`,periodLabel:period.period_start.slice(0,7),archived:plan.status==='archived'})
export const buildBudgetLimitCreatorViewModel=(month:string,plan?:BudgetLimitPlanRow,version?:BudgetLimitVersionRow):BudgetLimitCreatorViewModel=>({title:plan?'Edytuj limit':'Dodaj limit',submitLabel:plan?'Zapisz wersję':'Dodaj limit',draft:plan&&version?{id:plan.id,name:plan.name,scope_type:version.scope_type==='category_group'?'category_l2':version.scope_type,category_id:version.category_id,limit_amount:version.limit_amount,effective_month:month,alert_thresholds:version.alert_thresholds,forecast_alert_enabled:version.forecast_alert_enabled,status:plan.status==='archived'?'archived':'active'}:{name:'',scope_type:'category_l2',category_id:null,limit_amount:0,effective_month:month,alert_thresholds:[50,80,90],forecast_alert_enabled:true,status:'active'}})
export const buildBudgetLimitListViewModel=(items:Array<{plan:BudgetLimitPlanRow;version:BudgetLimitVersionRow;period:BudgetLimitPeriodRow;summary:BudgetLimitUsageSummary}>,categories:Record<string,Category>)=>items.map(item=>buildBudgetLimitCardViewModel(item.plan,item.version,item.period,item.summary,categories))
export const buildBudgetLimitHistoryViewModel=(items:Array<{period:BudgetLimitPeriodRow;summary:BudgetLimitUsageSummary}>,alerts:BudgetLimitAlertRow[]):BudgetLimitHistoryViewModel[]=>items.slice().sort((a,b)=>b.period.period_start.localeCompare(a.period.period_start)).map(item=>({periodId:item.period.id,month:item.period.period_start.slice(0,7),limitLabel:formatGrosze(item.summary.limitAmountGrosze),spentLabel:formatGrosze(item.summary.spentAmountGrosze),remainingLabel:formatGrosze(item.summary.remainingAmountGrosze),usagePercent:item.summary.usagePercent,status:item.summary.usageStatus,alerts:alerts.filter(alert=>alert.period_id===item.period.id).map(buildBudgetLimitAlertViewModel)}))
export const buildBudgetLimitDetailsViewModel=({plan,version,current,history,alerts,categories}:{plan:BudgetLimitPlanRow;version:BudgetLimitVersionRow;current:{period:BudgetLimitPeriodRow;summary:BudgetLimitUsageSummary;includedTransactions:Transaction[]};history:Array<{period:BudgetLimitPeriodRow;summary:BudgetLimitUsageSummary}>;alerts:BudgetLimitAlertRow[];categories:Record<string,Category>}):BudgetLimitDetailsViewModel=>({card:buildBudgetLimitCardViewModel(plan,version,current.period,current.summary,categories),transactions:current.includedTransactions,history:buildBudgetLimitHistoryViewModel(history,alerts),alerts:alerts.filter(alert=>alert.plan_id===plan.id).map(buildBudgetLimitAlertViewModel),thresholds:version.alert_thresholds,summary:current.summary})
