'use client'
import { useMemo, useState } from 'react'
import type { Category, Transaction } from '../lib/budgetPageTypes'
import type { BudgetLimitPlanDraft } from '../lib/budget-limits/data'
import { useBudgetLimitsData } from '../lib/budget-limits/useBudgetLimitsData'
import { buildBudgetLimitCreatorViewModel, buildBudgetLimitDetailsViewModel, buildBudgetLimitListViewModel } from '../lib/budget-limits/viewModels'
import { PrimaryAction, SecondaryAction } from './ui/FoundationPrimitives'

type Props={profileId:string;selectedMonth:string;categoriesById:Record<string,Category>;expenseLevel1Id:string|null;transactions:Transaction[];budgetStartDate?:string|null;getSignedAmountForTransaction:(transaction:Transaction)=>number}
export default function BudgetLimitsV1Panel(props:Props){
 const data=useBudgetLimitsData({...props});const[selectedId,setSelectedId]=useState<string|null>(null);const[draft,setDraft]=useState<BudgetLimitPlanDraft|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('')
 const selected=data.plans.find(plan=>plan.id===selectedId)||null;const selectedVersion=selected?(data.versions.filter(version=>version.plan_id===selected.id&&version.effective_from<=`${props.selectedMonth}-01`&&(!version.effective_to||version.effective_to>=`${props.selectedMonth}-01`)).at(-1)||data.versions.filter(version=>version.plan_id===selected.id).at(-1)||null):null
 const currentItems=useMemo(()=>data.plans.flatMap(plan=>{const matches=data.calculated.filter(item=>item.period.plan_id===plan.id);const item=matches.find(value=>value.period.period_start.slice(0,7)===props.selectedMonth)||(plan.status==='archived'?matches[0]:null);return item?[{...item,plan}]:[]}),[data.calculated,data.plans,props.selectedMonth]);const cards=buildBudgetLimitListViewModel(currentItems,props.categoriesById)
 const categoryOptions=Object.values(props.categoriesById).filter(category=>(category.level===2||category.level===3)&&getRoot(category.id,props.categoriesById)===props.expenseLevel1Id)
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await action()}catch(error){setNotice(error instanceof Error?error.message:'Operacja nie powiodła się')}finally{setBusy(false)}}
 if(data.error)return <div data-ui-empty-state="true">Moduł v1 wymaga migracji <code>budget_limits_stage_2.sql</code>. {data.error}</div>
 if(draft)return <section data-budget-limits-view="creator"><h3>{draft.id?'Edytuj limit':'Dodaj limit'}</h3><label>Nazwa<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Typ<select value={draft.scope_type} onChange={e=>setDraft({...draft,scope_type:e.target.value as BudgetLimitPlanDraft['scope_type'],category_id:e.target.value==='global_expenses'?null:draft.category_id})}><option value="category_l2">Miesięczny L2</option><option value="category_l3">Miesięczny L3</option><option value="global_expenses">Globalny Wydatki</option></select></label>{draft.scope_type!=='global_expenses'&&<label>Kategoria<select value={draft.category_id||''} onChange={e=>setDraft({...draft,category_id:e.target.value||null})}><option value="">Wybierz</option>{categoryOptions.filter(category=>category.level===(draft.scope_type==='category_l2'?2:3)).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label>}<label>Kwota limitu<input type="number" min="0.01" step="0.01" value={draft.limit_amount||''} onChange={e=>setDraft({...draft,limit_amount:Number(e.target.value)})}/></label><label>Okres miesięczny<input type="month" value={draft.effective_month} onChange={e=>setDraft({...draft,effective_month:e.target.value})}/></label><label>Progi alertów (%)<input value={draft.alert_thresholds.join(',')} onChange={e=>setDraft({...draft,alert_thresholds:normalizeThresholds(e.target.value)})}/></label><label><input type="checkbox" checked={draft.forecast_alert_enabled} onChange={e=>setDraft({...draft,forecast_alert_enabled:e.target.checked})}/> Alert ryzyka prognozy</label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as BudgetLimitPlanDraft['status']})}><option value="active">Aktywny</option><option value="archived">Archiwalny</option></select></label>{notice&&<p role="status">{notice}</p>}<PrimaryAction disabled={busy||!draft.name.trim()||draft.limit_amount<=0||(draft.scope_type!=='global_expenses'&&!draft.category_id)} onClick={()=>void run(async()=>{await(draft.id?data.updatePlan(draft):data.createPlan(draft));setDraft(null)})}>{draft.id?'Zapisz wersję':'Dodaj limit'}</PrimaryAction><SecondaryAction onClick={()=>setDraft(null)}>Anuluj</SecondaryAction></section>
 if(selected&&selectedVersion){const current=data.calculated.find(item=>item.period.plan_id===selected.id&&item.period.period_start.slice(0,7)===props.selectedMonth);if(current){const details=buildBudgetLimitDetailsViewModel({plan:selected,version:selectedVersion,current,history:data.calculated.filter(item=>item.period.plan_id===selected.id),alerts:data.alerts,categories:props.categoriesById});return <section data-budget-limits-view="details"><SecondaryAction onClick={()=>setSelectedId(null)}>Wróć do listy</SecondaryAction><h3>{details.card.name}</h3><p>{details.card.scopeLabel} · {details.card.periodLabel} · status: {details.card.status}</p><p>Limit {details.card.limitLabel} · wydano {details.card.spentLabel} · zostało {details.card.remainingLabel} · {details.card.usagePercent.toFixed(1)}%</p><progress max={100} value={details.card.usageBarPercent}/><p>{details.card.forecastLabel}</p><p>Progi: {details.thresholds.join('%, ')}%</p><PrimaryAction onClick={()=>setDraft(buildBudgetLimitCreatorViewModel(props.selectedMonth,selected,selectedVersion).draft)}>Edytuj</PrimaryAction><SecondaryAction disabled={busy||selected.status==='archived'} onClick={()=>void run(()=>data.archivePlan(selected.id))}>Archiwizuj</SecondaryAction>{notice&&<p role="status">{notice}</p>}<h4>Alerty</h4>{details.alerts.length===0?<p>Brak alertów.</p>:details.alerts.map(alert=><div key={alert.id}>{alert.label} · {alert.status}<button disabled={busy||alert.status!=='unread'} onClick={()=>void run(()=>data.markAlertRead(alert.raw))}>Oznacz jako przeczytane</button><button disabled={busy||alert.status==='muted'} onClick={()=>void run(()=>data.muteAlert(alert.raw))}>Wycisz dla okresu</button></div>)}<h4>Transakcje limitu</h4>{details.transactions.length===0?<p>Brak transakcji.</p>:details.transactions.map(transaction=><div key={transaction.id}>{transaction.date} · {transaction.description||'Bez opisu'} · {Number(transaction.amount).toFixed(2)}</div>)}<h4>Historia miesięczna</h4>{details.history.map(entry=><div key={entry.periodId}>{entry.month} · limit {entry.limitLabel} · wydano {entry.spentLabel} · zostało {entry.remainingLabel} · {entry.usagePercent.toFixed(1)}% · {entry.status} · alerty {entry.alerts.length}</div>)}</section>}}
 return <section data-budget-limits-view="list"><div><h3>Limity budżetowe</h3><PrimaryAction onClick={()=>setDraft(buildBudgetLimitCreatorViewModel(props.selectedMonth).draft)}>Dodaj limit</PrimaryAction></div>{notice&&<p role="status">{notice}</p>}{data.loading?<p>Ładowanie…</p>:cards.length===0?<p>Brak limitów w tym miesiącu.</p>:cards.map(card=><button key={card.id} type="button" data-ui-card="true" onClick={()=>setSelectedId(card.id)}><strong>{card.name}</strong><span>{card.scopeLabel} · {card.periodLabel}</span><span>{card.spentLabel} / {card.limitLabel} · zostało {card.remainingLabel} · {card.usagePercent.toFixed(1)}% · {card.status}</span><progress max={100} value={card.usageBarPercent}/><span>{card.forecastLabel}</span></button>)}</section>
}
const getRoot=(id:string,categories:Record<string,Category>)=>{let current=categories[id];while(current?.parent_id)current=categories[current.parent_id];return current?.id||null}
const normalizeThresholds=(text:string)=>[...new Set(text.split(',').map(value=>Number(value.trim())).filter(value=>Number.isInteger(value)&&value>0&&value<100))].sort((a,b)=>a-b)
