'use client'

import { useTransactionOperations } from '../lib/useTransactionOperations'
import { useCategoryVisibilityActions } from '../lib/useCategoryVisibilityActions'
import { useTransactionEntryActions } from '../lib/useTransactionEntryActions'
import { getCategoryPathLabel } from '../lib/budgetPageHelpers'
import { Transaction } from '../lib/budgetPageTypes'
import { supabase } from '../lib/supabaseClient'
import { getAmountNumber } from '../lib/transactionUtils'
import { useBudgetTreeSorting } from '../lib/useBudgetTreeSorting'
import { useBudgetPageActions } from '../lib/useBudgetPageActions'
import { useBudgetMoveTargetsData } from '../lib/useBudgetMoveTargetsData'
import { canCreateTransactionsInMonth } from '../lib/transactionCreationAvailability'
import { useRecurringTransactions } from '../lib/useRecurringTransactions'
import { useFinancialGoals } from '../lib/useFinancialGoals'
import { isAllowedMoveTarget as checkIsAllowedMoveTarget } from '../lib/isAllowedMoveTarget'
import { useBudgetPageData } from '../lib/useBudgetPageData'
import { useBudgetAppEffects } from './budget-app/useBudgetAppEffects'
import BudgetAppControllerView from './budget-app/BudgetAppControllerView'
import { useBudgetAppControllerViewProps } from './budget-app/useBudgetAppControllerViewProps'
import { useBudgetLimitViews } from './budget-app/useBudgetLimitViews'
import { usePinnedCategories } from './budget-app/usePinnedCategories'
import { usePreviousMonthReminder } from './budget-app/usePreviousMonthReminder'
import { useBudgetAppCoreState } from './budget-app/useBudgetAppCoreState'
import { useBudgetAppShellState } from './budget-app/useBudgetAppShellState'
import { useBudgetAppTransactionCreatorState } from './budget-app/useBudgetAppTransactionCreatorState'
import { useBudgetAppMonthDangerHandlers } from './budget-app/useBudgetAppMonthDangerHandlers'
import { useBudgetAppRecurringOptionsBridge } from './budget-app/useBudgetAppRecurringOptionsBridge'
import { useBudgetAppTransactionCreatorBridge } from './budget-app/useBudgetAppTransactionCreatorBridge'
import { useBudgetAppPaymentSourcesBridge } from './budget-app/useBudgetAppPaymentSourcesBridge'
import { useBudgetAppWorkspaceDataBridge } from './budget-app/useBudgetAppWorkspaceDataBridge'

export type BudgetAppProps = {
  profileId: string
  userId: string
  userEmail: string
  signOut: () => Promise<void>
  inviteEmail: string
  setInviteEmail: (value: string) => void
  inviteLink: string
  invitationStatusText: string
  invitationErrorText: string
  isInvitationWorking: boolean
  createInvitation: () => Promise<void>
  copyInviteLink: () => Promise<void>
  onCurrentUserLeftProfile: () => Promise<void>
}

export default function BudgetAppController({
  profileId,
  userId,
  userEmail,
  signOut,
  inviteEmail,
  setInviteEmail,
  inviteLink,
  invitationStatusText,
  invitationErrorText,
  isInvitationWorking,
  createInvitation,
  copyInviteLink,
  onCurrentUserLeftProfile,
}: BudgetAppProps) {
  const {
    activeSidebarPrimaryPanel,
    activeUtilityPanel,
    activeScopeTransactions,
    amountInputRef,
    budgetLimitEditorCategoryId,
    categories,
    descriptionInputRef,
    errorText,
    isDashboardPanelOpen,
    isSaving,
    migrationPromptState,
    newSubcategoryIconKey,
    newSubcategoryName,
    openAddSubcategoryFor,
    searchPanelRef,
    setActiveSidebarPrimaryPanel,
    setActiveUtilityPanel,
    setActiveScopeTransactions,
    setBudgetLimitEditorCategoryId,
    setCategories,
    setErrorText,
    setIsDashboardPanelOpen,
    setIsSaving,
    setMigrationPromptState,
    setNewSubcategoryIconKey,
    setNewSubcategoryName,
    setOpenAddSubcategoryFor,
    setShowHiddenCategories,
    setStatus,
    setTags,
    setTransactionPaymentSplitsMap,
    setTransactionTagsMap,
    setTransactions,
    setTrashedTransactions,
    showHiddenCategories,
    status,
    styles,
    tags,
    transactionPaymentSplitsMap,
    transactionTagsMap,
    transactions,
    trashedTransactions,
  } = useBudgetAppCoreState()

  const {
    effectiveVisibleModules,
    isBudgetLimitsModuleEnabled,
    isFinancialGoalsModuleEnabled,
    isMonthCalendarModuleEnabled,
    isPaymentSourcesModuleEnabled,
    isRecurringTransactionsModuleEnabled,
    isSettingsPanelVisible,
    moduleVisibility,
    monthNavigation,
    activeScopeTransactions: scopedActiveScopeTransactions,
    scopedTransactions,
    setIsSettingsPanelVisible,
  } = useBudgetAppShellState({
    profileId,
    userId,
    transactions,
    activeScopeTransactions,
    activeSidebarPrimaryPanel,
    setActiveSidebarPrimaryPanel,
    activeUtilityPanel,
    setActiveUtilityPanel,
  })

  const {
    visibleModules,
    draftVisibleModules,
    saveStatusText: moduleVisibilitySaveStatusText,
    setDraftModuleVisibility,
    saveVisibleModules,
    resetDraftVisibleModules,
  } = moduleVisibility

  const {
    selectedMonth,
    setSelectedMonth,
    currentMonth,
    setMonthNavigationStartMonth,
    budgetStartDate,
    savedBudgetStartDate,
    setBudgetStartDate,
    isFutureMonthNavigationLocked,
    setIsFutureMonthNavigationLocked,
    simpleMode,
    setSimpleMode,
    calendarHeatmapVariant,
    setCalendarHeatmapVariant,
    heatmapMode,
    setHeatmapMode,
    heatmapInverted,
    setHeatmapInverted,
    autoExcludePartialMonths,
    setAutoExcludePartialMonths,
    isSavingMonthNavigationSettings,
    monthNavigationErrorText,
    setMonthNavigationErrorText,
    lockedMonthsSet,
    excludedMonthsSet,
    isUpdatingSelectedMonthLock,
    isSelectedMonthLocked,
    isUpdatingSelectedMonthExclusion,
    isSelectedMonthExcluded,
    minAllowedMonth,
    maxAllowedMonth,
    isPrevMonthNavigationBlocked,
    isNextMonthNavigationBlocked,
    loadMonthNavigationSettings,
    loadLockedMonths,
    loadExcludedMonths,
    handleSaveMonthNavigationSettings,
    handleLockSelectedMonth,
    handleUnlockSelectedMonth,
    handleToggleSelectedMonthExcluded,
    handleLockAllPastMonths,
    handleUnlockAllPastMonths,
    handleLockMonth,
    goToPrevMonth,
    goToNextMonth,
  } = monthNavigation

  const {
    effectiveQuickDayDate,
    isQuickDayModeEnabled,
    isSerialTransactionCreatorEnabled,
    isTransactionCreatorOpen,
    newAmount,
    newDescription,
    newTransactionDate,
    selectedLevel2Id,
    selectedPaymentSourceId,
    selectedPaymentSplitItems,
    selectedRecurringTransactionId,
    selectedTagNames,
    selectedTransactionCategoryId,
    selectedTransactionTypeId,
    setIsQuickDayModeEnabled,
    setIsSerialTransactionCreatorEnabled,
    setIsTransactionCreatorOpen,
    setNewAmount,
    setNewDescription,
    setNewTransactionDate,
    setQuickDayDate,
    setSelectedLevel2Id,
    setSelectedPaymentSourceId,
    setSelectedPaymentSplitItems,
    setSelectedRecurringTransactionId,
    setSelectedTagNames,
    setSelectedTransactionCategoryId,
    setSelectedTransactionTypeId,
    setTransactionCreatorInitialDate,
    setTransactionCreatorLockedLevel1Id,
    setTransactionCreatorSuggestionId,
    transactionCreatorInitialDate,
    transactionCreatorLockedLevel1Id,
    transactionCreatorSuggestionId,
  } = useBudgetAppTransactionCreatorState({ selectedMonth })
  const {
    selectedTransactionIds,
    setSelectedTransactionIds,
    bulkMoveTargetCategoryId,
    setBulkMoveTargetCategoryId,
    bulkActionErrorText,
    setBulkActionErrorText,
    lastUndoAction,
    setLastUndoAction,
    clearTransactionSelection,
    clearTransactionOperationUi,
    toggleTransactionSelection,
    guardMonthUnlocked,
    guardTransactionsUnlocked,
    handleBulkDeleteSelected,
    handleBulkMoveSelected,
    handleUndoLastAction,
  } = useTransactionOperations({
    profileId,
    lockedMonthsSet,
    setMigrationPromptState,
  })

  const {
    activeBudgetLimitAlerts,
    activeBudgetLimits,
    activeLimitStates,
    addBudgetLimit,
    addableTransactionCategoryIds,
    applyTransactionCategorySelection,
    bankSearchCategoryOptions,
    bankSearchResults,
    bankSearchState,
    bankSearchSummary,
    bankSearchTagOptions,
    categoriesById,
    deleteBudgetLimit,
    descriptionSuggestions,
    expenseLevel1Id,
    getCalendarHeatmapVariantForLevel1Id,
    getCategoryCountForSelectedMonth,
    getCountForLevel2ForSelectedMonth,
    getRootLevel1IdForCategory,
    getSignedAmountForTransaction,
    getSumForCategoryForSelectedMonth,
    getSumForLevel2ForSelectedMonth,
    getTransactionsForCategoryAndMonthForSelectedMonth,
    getTransactionsForLevel1AndMonth,
    handleBankSearchFieldChange,
    handleDeleteDescriptionSuggestion,
    handleOpenSearchForTag,
    handleResetHeatmapSettings,
    hiddenCategoriesInSelectedMonth,
    incomeLevel1Id,
    isBankSearchOpen,
    level1,
    level2,
    level2ByParentId,
    level3ByParentId,
    loadBudgetLimits,
    openLevel1CalendarIds,
    openLevel1Ids,
    openLevel2Ids,
    openLevel3Ids,
    recentTransactionShortcutCategoriesByType,
    resetBankSearch,
    resetTreeOpenState,
    restoreDescriptionSuggestion,
    selectedMonthTransactions,
    setIsBankSearchOpen,
    setOpenLevel1Ids,
    setOpenLevel2Ids,
    setOpenLevel3Ids,
    sortedLevel1,
    topTransactionShortcutCategoriesByType,
    toggleLevel1,
    toggleLevel1Calendar,
    toggleLevel2,
    toggleLevel3,
    transactionCategoryPathLabels,
    updateBudgetLimit,
    visibleCategories,
  } = useBudgetAppWorkspaceDataBridge({
    profileId,
    scopedTransactions,
    activeScopeTransactions: scopedActiveScopeTransactions,
    selectedMonth,
    categories,
    isBudgetLimitsModuleEnabled,
    heatmapMode,
    setHeatmapMode,
    heatmapInverted,
    setHeatmapInverted,
    excludedMonthsSet,
    isPaymentSourcesModuleEnabled,
    userId,
    transactionPaymentSplitsMap,
    tags,
    transactionTagsMap,
    searchPanelRef,
    setSelectedTransactionTypeId,
    setSelectedLevel2Id,
    setSelectedTransactionCategoryId,
  })
  const canCreateTransactions = canCreateTransactionsInMonth(isSelectedMonthLocked)

  const {
    bankSearchPaymentSourceOptions,
    copyPaymentSourcesBetweenKinds,
    currentTransactionCreatorDefaultPaymentSourceId,
    currentTransactionCreatorKind,
    currentTransactionCreatorPaymentSourceOptions,
    deletePaymentSource,
    getDefaultPaymentSourceIdForCategoryId,
    getPaymentSourceKindForLevel1Id,
    getPaymentSourceOptionsForCategoryId,
    incomePaymentSourceOptions,
    isTransactionCreatorPaymentSourceVisible,
    loadPaymentSources,
    paymentSourceOptions,
    paymentSourceSettings,
    paymentSourceStats,
    paymentSources,
    savePaymentSource,
    setDefaultPaymentSource,
    setPaymentSourceFieldVisibility,
    setSelectedTransactionTypeIdWithPaymentSource,
  } = useBudgetAppPaymentSourcesBridge({
    profileId,
    scopedTransactions,
    transactionPaymentSplitsMap,
    categoriesById,
    incomeLevel1Id,
    expenseLevel1Id,
    getRootLevel1IdForCategory,
    getSignedAmountForTransaction,
    selectedPaymentSourceId,
    setSelectedPaymentSourceId,
    isPaymentSourcesModuleEnabled,
    selectedTransactionTypeId,
    transactionCreatorLockedLevel1Id,
    setSelectedTransactionTypeId,
  })
  const {
    pinnedCategoryIds,
    pinnedTransactionShortcutCategoriesByType,
    togglePinnedCategory,
  } = usePinnedCategories({
    userId,
    profileId,
    addableTransactionCategoryIds,
    transactionCategoryPathLabels,
    getRootLevel1IdForCategory,
  })

  const {
    recurringTransactions,
    recurringExecutions,
    recurringReminderMonthStatuses,
    loadRecurringTransactions,
    saveRecurringTransaction,
    deleteRecurringTransaction,
    saveRecurringExecution,
    saveRecurringReminderMonthStatus,
  } = useRecurringTransactions({
    profileId,
    selectedMonth,
    isEnabled: isRecurringTransactionsModuleEnabled,
  })

  const {
    financialGoals,
    financialGoalPriorities,
    financialGoalMonthConfigs,
    loadFinancialGoals,
    saveFinancialGoal,
    deleteFinancialGoal,
    setGoalModeForMonth,
    saveGoalPrioritiesForMonth,
    saveGoalAllocationsForMonth,
  } = useFinancialGoals({
    profileId,
    isEnabled: isFinancialGoalsModuleEnabled,
  })

  const {
    applyDraftToTransactionCreator,
    cleanupAllDrafts,
    deleteDraft,
    draftPromptState,
    drafts,
    draftsStatusText,
    formatDraftUpdatedAt,
    getDraftLevel1Id,
    getDraftLocationLabel,
    handleDuplicateTransaction,
    handleOpenCategoryCalendarAddForDay,
    handleOpenGlobalCalendarAddForDay,
    handleOpenLevel1CalendarAddForDay,
    handleTransactionSavedWithReminderStatus,
    isCleaningAllDrafts,
    isDraftsLoading,
    loadDrafts,
    openBlankFloatingTransactionCreator,
    openFloatingTransactionCreator,
    openReminderTransactionCreator,
    openTransactionCreator,
    resetTransactionCreator,
    saveDraft,
    setDraftPromptState,
    transactionDraftType,
  } = useBudgetAppTransactionCreatorBridge({
    profileId,
    categoriesById,
    incomeLevel1Id,
    expenseLevel1Id,
    selectedMonth,
    isTransactionCreatorOpen,
    selectedTransactionTypeId,
    selectedLevel2Id,
    selectedTransactionCategoryId,
    newAmount,
    newDescription,
    newTransactionDate,
    transactionCreatorInitialDate,
    applyTransactionCategorySelection,
    setSelectedMonth,
    setTransactionCreatorSuggestionId,
    setTransactionCreatorLockedLevel1Id,
    setSelectedTransactionTypeIdWithPaymentSource,
    setSelectedLevel2Id,
    setSelectedTransactionCategoryId,
    setNewAmount,
    setNewDescription,
    setNewTransactionDate,
    setSelectedRecurringTransactionId,
    setIsSerialTransactionCreatorEnabled,
    setTransactionCreatorInitialDate,
    setIsTransactionCreatorOpen,
    amountInputRef,
    descriptionInputRef,
    isRecurringTransactionsModuleEnabled,
    recurringTransactions,
    recurringExecutions,
    scopedTransactions,
    selectedRecurringTransactionId,
    paymentSourceSettings,
    getRootLevel1IdForCategory,
    getPaymentSourceKindForLevel1Id,
    saveRecurringReminderMonthStatus,
    setSelectedPaymentSourceId,
    setSelectedPaymentSplitItems,
    setSelectedTagNames,
    restoreDescriptionSuggestion,
    isSelectedMonthLocked,
    isQuickDayModeEnabled,
    effectiveQuickDayDate,
    transactionTagsMap,
    transactionPaymentSplitsMap,
    effectiveVisibleModules,
  })
  const { loadData } = useBudgetPageData({
    profileId,
    selectedMonth,
    budgetStartDate: savedBudgetStartDate,
    setStatus,
    setErrorText,
    setCategories,
    setTransactions,
    setActiveScopeTransactions,
    setTrashedTransactions,
    setTransactionPaymentSplitsMap,
    setTransactionTagsMap,
    setTags,
    resetTreeOpenState,
    loadMonthNavigationSettings,
    loadLockedMonths,
    loadExcludedMonths,
    loadPaymentSources,
    loadRecurringTransactions,
    loadFinancialGoals,
    loadDrafts,
    isPaymentSourcesEnabled: isPaymentSourcesModuleEnabled,
  })

  const {
    handleImportTransactions,
    handleAddSubcategory,
    handleRenameCategory,
    handleUpdateCategoryIcon,
    handleDeleteCategory,
  } = useBudgetPageActions({
    profileId,
    selectedMonth,
    guardMonthUnlocked,
    categories,
    transactions: scopedTransactions,
    isPaymentSourcesEnabled: isPaymentSourcesModuleEnabled,
    newSubcategoryName,
    newSubcategoryIconKey,
    setOpenAddSubcategoryFor,
    setNewSubcategoryName,
    setNewSubcategoryIconKey,
    loadData,
  })

  const {
    handleResetAllHistory,
    handleResetSelectedMonthData,
    handleSaveMonthNavigationSettingsWithStartDateWarning,
    handleToggleSelectedMonthExcludedWithConfirm,
  } = useBudgetAppMonthDangerHandlers({
    supabase,
    profileId,
    selectedMonth,
    budgetStartDate,
    savedBudgetStartDate,
    transactions: scopedActiveScopeTransactions,
    scopedTransactions,
    selectedMonthTransactions,
    isSelectedMonthExcluded,
    handleSaveMonthNavigationSettings,
    handleToggleSelectedMonthExcluded,
    clearTransactionOperationUi,
    clearTransactionSelection,
    resetTransactionCreator,
    loadData,
  })
  const isAllowedMoveTarget = (transaction: Transaction, targetCategoryId: string) => {
    return checkIsAllowedMoveTarget(
      transaction,
      targetCategoryId,
      categories,
      categoriesById,
      getRootLevel1IdForCategory
    )
  }

  const {
    getMoveTargetsForTransaction,
    getCommonMoveTargetsForTransactions,
    selectedTransactions,
    commonBulkMoveTargets,
    migrationPromptTransactions,
    migrationPromptMoveTargets,
    activeTransactionsById,
    trashedTransactionsById,
  } = useBudgetMoveTargetsData({
    transactions: scopedTransactions,
    trashedTransactions,
    categories,
    categoriesById,
    selectedTransactionIds,
    migrationPromptState,
    isAllowedMoveTarget,
  })

  const {
    handleSaveTransaction,
    handleInlineSaveTransaction,
    handleUpdateTransaction,
    moveTransactionsToCategory,
    handleRestoreTransaction,
    handleMoveTransaction,
    handleDeleteTransaction,
    handlePermanentDeleteTransaction,
    handleEmptyTrash,
  } = useTransactionEntryActions({
    supabase,
    profileId,
    selectedMonth,
    visibleCategories,
    categoriesById,
    activeTransactionsById,
    trashedTransactionsById,
    transactionDraftType,
    selectedTransactionTypeId,
    selectedLevel2Id,
    selectedTransactionCategoryId,
    newAmount,
    newDescription,
    newTransactionDate,
    selectedRecurringTransactionId,
    isSerialTransactionCreatorEnabled,
    isQuickDayModeEnabled,
    quickDayDate: effectiveQuickDayDate,
    isPaymentSourcesEnabled: isPaymentSourcesModuleEnabled,
    isRecurringTransactionsEnabled: isRecurringTransactionsModuleEnabled,
    isAllowedMoveTarget,
    getRootLevel1IdForCategory,
    deleteDraft,
    guardMonthUnlocked,
    guardTransactionsUnlocked,
    clearTransactionOperationUi,
    loadData,
    resetTransactionCreator,
    setLastUndoAction,
    setTransactions,
    setIsSaving,
    setTransactionCreatorSuggestionId,
    setNewTransactionDate,
    setNewAmount,
    setNewDescription,
    setSelectedTagNames,
    setSelectedPaymentSourceId,
    setSelectedPaymentSplitItems,
    defaultPaymentSourceId: currentTransactionCreatorDefaultPaymentSourceId,
    onTransactionSaved: handleTransactionSavedWithReminderStatus,
    amountInputRef,
    selectedTagNames,
    selectedPaymentSourceId,
    selectedPaymentSplitItems,
    transactionTagsMap,
  })

  const {
    handleConfirmCategoryMigration,
    handleHideCategory,
    handleUndoScheduledHide,
    handleRestoreCategory,
  } = useCategoryVisibilityActions({
    supabase,
    profileId,
    categories,
    transactions: scopedTransactions,
    selectedMonth,
    activeTransactionsById,
    loadData,
    clearTransactionOperationUi,
    clearTransactionSelection,
    resetTransactionCreator,
    moveTransactionsToCategory,
    getCommonMoveTargetsForTransactions,
    setMigrationPromptState,
    setLastUndoAction,
    setOpenAddSubcategoryFor,
    setNewSubcategoryName,
    setNewSubcategoryIconKey,
  })

  const {
    previousMonthCloseReminder,
    setCurrentDayOfMonth,
    setIsPreviousMonthCloseReminderHidden,
  } = usePreviousMonthReminder({
    currentMonth,
    lockedMonthsSet,
  })

  useBudgetAppEffects({
    loadData,
    loadBudgetLimits,
    setErrorText,
    setCurrentDayOfMonth,
    scopedTransactions,
    setSelectedTransactionIds,
    bulkMoveTargetCategoryId,
    commonBulkMoveTargets,
    setBulkMoveTargetCategoryId,
    migrationPromptState,
    migrationPromptMoveTargets,
    setMigrationPromptState,
  })

  const {
    level2SortMode,
    setLevel2SortMode,
    level2SortDirection,
    setLevel2SortDirection,
    level3SortMode,
    setLevel3SortMode,
    level3SortDirection,
    setLevel3SortDirection,
    isReorderingLevel1,
    reorderingLevel1Id,
    reorderingLevel2Id,
    getSortedLevel2Children,
    getSortedLevel3Children,
    sortedLevel2ByParentIdForModal,
    sortedLevel3ByParentIdForModal,
    handleReorderLevel1,
    handleReorderLevel2,
    handleReorderLevel3,
    handleLevel1DragStart,
    handleLevel3DragStart,
  } = useBudgetTreeSorting({
    profileId,
    userId,
    categories,
    setCategories,
    openLevel1Ids,
    openLevel2Ids,
    setOpenLevel1Ids,
    setOpenLevel2Ids,
    setOpenLevel3Ids,
    level1,
    level2,
    level2ByParentId,
    level3ByParentId,
    getSumForCategoryForSelectedMonth,
    getSumForLevel2ForSelectedMonth,
    getCountForLevel2ForSelectedMonth,
    getCategoryCountForSelectedMonth,
  })

  const {
    finalCategoryOptions,
    getRecurringOptionsForCategoryId,
    recurringOptionItems,
    recurringSuggestionItems,
  } = useBudgetAppRecurringOptionsBridge({
    visibleCategories,
    recurringTransactions,
    recurringExecutions,
    recurringReminderMonthStatuses,
    transactions: scopedTransactions,
    selectedMonth,
    selectedTransactionCategoryId,
    selectedLevel2Id,
    selectedTransactionTypeId,
    newAmount,
    newDescription,
    categoriesById,
    isEnabled: effectiveVisibleModules.recurringTransactions,
  })
  const getBudgetLimitView = useBudgetLimitViews(activeLimitStates)

  const {
    budgetLimitDataSnapshot,
    statusPanelsCtx,
    rightRailProps,
    mainPanelsProps,
    dashboardDrawerProps,
    overlaySectionProps,
  } = useBudgetAppControllerViewProps({
    activeBudgetLimitAlerts, activeScopeTransactions: scopedActiveScopeTransactions, activeBudgetLimits, activeTransactionsById, activeUtilityPanel, addableTransactionCategoryIds, applyDraftToTransactionCreator, bankSearchCategoryOptions, bankSearchPaymentSourceOptions, bankSearchResults, bankSearchState,
    bankSearchSummary, bankSearchTagOptions, budgetStartDate, bulkActionErrorText, bulkMoveTargetCategoryId, calendarHeatmapVariant, canCreateTransactions, categories, categoriesById, cleanupAllDrafts,
    clearTransactionOperationUi, clearTransactionSelection, commonBulkMoveTargets, copyPaymentSourcesBetweenKinds, currentTransactionCreatorKind, deleteDraft, deleteFinancialGoal, deletePaymentSource, deleteRecurringTransaction, descriptionSuggestions, drafts,
    draftsStatusText, effectiveVisibleModules, errorText, expenseLevel1Id, finalCategoryOptions, financialGoalMonthConfigs, financialGoalPriorities, financialGoals, formatDraftUpdatedAt, getAmountNumber,
    getBudgetLimitView, getCalendarHeatmapVariantForLevel1Id, getCategoryPathLabel, getCountForLevel2ForSelectedMonth, getDefaultPaymentSourceIdForCategoryId, getDraftLevel1Id, getDraftLocationLabel, getMoveTargetsForTransaction, getPaymentSourceOptionsForCategoryId, getRecurringOptionsForCategoryId,
    getSignedAmountForTransaction, getRootLevel1IdForCategory, getSortedLevel2Children, getSortedLevel3Children, getSumForCategoryForSelectedMonth, getSumForLevel2ForSelectedMonth, getTransactionsForCategoryAndMonthForSelectedMonth, getTransactionsForLevel1AndMonth, handleAddSubcategory, handleBankSearchFieldChange,
    handleBulkDeleteSelected, handleBulkMoveSelected, handleConfirmCategoryMigration, handleDeleteCategory, handleDeleteDescriptionSuggestion, handleDeleteTransaction, handleDuplicateTransaction, handleEmptyTrash, handleHideCategory, handleImportTransactions,
    handleInlineSaveTransaction, handleLevel1DragStart, handleLevel3DragStart, handleLockMonth, handleMoveTransaction, handleOpenCategoryCalendarAddForDay, handleOpenGlobalCalendarAddForDay, handleOpenLevel1CalendarAddForDay, handleOpenSearchForTag, handlePermanentDeleteTransaction,
    handleRenameCategory, handleUpdateCategoryIcon, handleReorderLevel1, handleReorderLevel2, handleReorderLevel3, handleRestoreCategory, handleRestoreTransaction, handleToggleSelectedMonthExcludedWithConfirm, handleUndoLastAction, handleUndoScheduledHide, handleUpdateTransaction,
    heatmapInverted, heatmapMode, hiddenCategoriesInSelectedMonth, incomeLevel1Id, isAllowedMoveTarget, isBankSearchOpen, isBudgetLimitsModuleEnabled, isCleaningAllDrafts, isDraftsLoading, isMonthCalendarModuleEnabled,
    isPaymentSourcesModuleEnabled, isRecurringTransactionsModuleEnabled, isReorderingLevel1, isSelectedMonthExcluded, isSelectedMonthLocked, isTransactionCreatorPaymentSourceVisible, isUpdatingSelectedMonthExclusion, lastUndoAction, level2SortDirection, level2SortMode,
    level3SortDirection, level3SortMode, loadData, lockedMonthsSet, migrationPromptMoveTargets, migrationPromptState, migrationPromptTransactions, newSubcategoryIconKey, newSubcategoryName, openAddSubcategoryFor, openBlankFloatingTransactionCreator,
    openLevel1CalendarIds, openLevel1Ids, openLevel2Ids, openLevel3Ids, openReminderTransactionCreator, openTransactionCreator, paymentSourceOptions, paymentSourceSettings, paymentSourceStats, paymentSources,
    previousMonthCloseReminder, profileId, recurringExecutions, recurringTransactions, reorderingLevel1Id, reorderingLevel2Id, resetBankSearch, saveDraft, saveFinancialGoal, saveGoalAllocationsForMonth, saveGoalPrioritiesForMonth,
    savePaymentSource, saveRecurringExecution, saveRecurringTransaction, scopedTransactions, searchPanelRef, selectedMonth, selectedMonthTransactions, selectedPaymentSourceId, selectedTransactionCategoryId, selectedTransactionIds,
    selectedTransactions, setActiveUtilityPanel, setBudgetLimitEditorCategoryId, setBulkActionErrorText, setBulkMoveTargetCategoryId, setDefaultPaymentSource, setGoalModeForMonth, setHeatmapInverted, setHeatmapMode, setIsBankSearchOpen,
    setIsPreviousMonthCloseReminderHidden, setLevel2SortDirection, setLevel2SortMode, setLevel3SortDirection, setLevel3SortMode, setMigrationPromptState, setNewSubcategoryIconKey, setNewSubcategoryName, setNewTransactionDate, setOpenAddSubcategoryFor, setPaymentSourceFieldVisibility,
    setSelectedPaymentSourceId, showHiddenCategories, sortedLevel1, status, styles, supabase, toggleLevel1, toggleLevel1Calendar, toggleLevel2, toggleLevel3,
    toggleTransactionSelection, transactionCategoryPathLabels, transactionPaymentSplitsMap, transactionTagsMap, transactions, trashedTransactions, trashedTransactionsById, userId, visibleModules, autoExcludePartialMonths,
    copyInviteLink, createInvitation, currentMonth, draftVisibleModules, goToNextMonth, goToPrevMonth, handleLockAllPastMonths, handleLockSelectedMonth, handleResetAllHistory, handleResetHeatmapSettings,
    handleResetSelectedMonthData, handleSaveMonthNavigationSettingsWithStartDateWarning, handleUnlockAllPastMonths, handleUnlockSelectedMonth, invitationErrorText, invitationStatusText, inviteEmail, inviteLink, isDashboardPanelOpen, isFutureMonthNavigationLocked,
    isInvitationWorking, isNextMonthNavigationBlocked, isPrevMonthNavigationBlocked, isSavingMonthNavigationSettings, activeSidebarPrimaryPanel, isSettingsPanelVisible, isUpdatingSelectedMonthLock, maxAllowedMonth, minAllowedMonth, moduleVisibilitySaveStatusText, monthNavigationErrorText,
    onCurrentUserLeftProfile, resetDraftVisibleModules, saveVisibleModules, setActiveSidebarPrimaryPanel, setAutoExcludePartialMonths, setBudgetStartDate, setCalendarHeatmapVariant, setDraftModuleVisibility, setInviteEmail, setIsDashboardPanelOpen, setIsFutureMonthNavigationLocked,
    setIsSettingsPanelVisible, setMonthNavigationErrorText, setMonthNavigationStartMonth, setSelectedMonth, setShowHiddenCategories, setSimpleMode, signOut, simpleMode, userEmail, visibleCategories,
    addBudgetLimit, amountInputRef, applyTransactionCategorySelection, budgetLimitEditorCategoryId, currentTransactionCreatorPaymentSourceOptions, deleteBudgetLimit, descriptionInputRef, draftPromptState, excludedMonthsSet, handleSaveTransaction,
    incomePaymentSourceOptions, isQuickDayModeEnabled, isSaving, isSerialTransactionCreatorEnabled, isTransactionCreatorOpen, level1, newAmount, newDescription, newTransactionDate, openFloatingTransactionCreator,
    pinnedCategoryIds, pinnedTransactionShortcutCategoriesByType, recentTransactionShortcutCategoriesByType, recurringOptionItems, recurringSuggestionItems, resetTransactionCreator, selectedLevel2Id, selectedPaymentSplitItems, selectedRecurringTransactionId, selectedTagNames,
    selectedTransactionTypeId, setDraftPromptState, setErrorText, setIsQuickDayModeEnabled, setIsSerialTransactionCreatorEnabled, setNewAmount, setNewDescription, setQuickDayDate, setSelectedLevel2Id, setSelectedPaymentSplitItems,
    setSelectedRecurringTransactionId, setSelectedTagNames, setSelectedTransactionCategoryId, setSelectedTransactionTypeIdWithPaymentSource, sortedLevel2ByParentIdForModal, sortedLevel3ByParentIdForModal, topTransactionShortcutCategoriesByType, togglePinnedCategory, updateBudgetLimit, activeLimitStates,
    transactionCreatorLockedLevel1Id, transactionCreatorSuggestionId,
  })
  return (
    <BudgetAppControllerView
      styles={styles}
      budgetLimitDataSnapshot={budgetLimitDataSnapshot}
      statusPanelsCtx={statusPanelsCtx}
      rightRailProps={rightRailProps}
      mainPanelsProps={mainPanelsProps}
      dashboardDrawerProps={dashboardDrawerProps}
      overlaySectionProps={overlaySectionProps}
    />
  )
}
