export const LETTER_ICON_OPTIONS = [
  { key: "letter-a", character: "A", label: "Litera A" },
  { key: "letter-b", character: "B", label: "Litera B" },
  { key: "letter-c", character: "C", label: "Litera C" },
  { key: "letter-ć", character: "Ć", label: "Litera Ć" },
  { key: "letter-d", character: "D", label: "Litera D" },
  { key: "letter-e", character: "E", label: "Litera E" },
  { key: "letter-f", character: "F", label: "Litera F" },
  { key: "letter-g", character: "G", label: "Litera G" },
  { key: "letter-h", character: "H", label: "Litera H" },
  { key: "letter-i", character: "I", label: "Litera I" },
  { key: "letter-j", character: "J", label: "Litera J" },
  { key: "letter-k", character: "K", label: "Litera K" },
  { key: "letter-l", character: "L", label: "Litera L" },
  { key: "letter-ł", character: "Ł", label: "Litera Ł" },
  { key: "letter-m", character: "M", label: "Litera M" },
  { key: "letter-n", character: "N", label: "Litera N" },
  { key: "letter-ń", character: "Ń", label: "Litera Ń" },
  { key: "letter-o", character: "O", label: "Litera O" },
  { key: "letter-p", character: "P", label: "Litera P" },
  { key: "letter-q", character: "Q", label: "Litera Q" },
  { key: "letter-r", character: "R", label: "Litera R" },
  { key: "letter-s", character: "S", label: "Litera S" },
  { key: "letter-ś", character: "Ś", label: "Litera Ś" },
  { key: "letter-t", character: "T", label: "Litera T" },
  { key: "letter-u", character: "U", label: "Litera U" },
  { key: "letter-v", character: "V", label: "Litera V" },
  { key: "letter-w", character: "W", label: "Litera W" },
  { key: "letter-x", character: "X", label: "Litera X" },
  { key: "letter-y", character: "Y", label: "Litera Y" },
  { key: "letter-z", character: "Z", label: "Litera Z" },
  { key: "letter-ź", character: "Ź", label: "Litera Ź" },
  { key: "letter-ż", character: "Ż", label: "Litera Ż" },
] as const;

export type LetterIconKey = (typeof LETTER_ICON_OPTIONS)[number]["key"];
export type LetterIconCharacter =
  (typeof LETTER_ICON_OPTIONS)[number]["character"];

export const FINAL_USER_ICON_OPTIONS = [
  { key: "note", label: "Notatka" },
  { key: "exchange", label: "Wymiana" },
  { key: "home", label: "Dom" },
  { key: "food", label: "Jedzenie" },
  { key: "restaurant", label: "Restauracja" },
  { key: "coffee", label: "Kawa" },
  { key: "shopping", label: "Zakupy" },
  { key: "car", label: "Samochód" },
  { key: "transport", label: "Transport" },
  { key: "fuel", label: "Paliwo" },
  { key: "parking", label: "Parking" },
  { key: "taxi", label: "Taxi" },
  { key: "plane", label: "Samolot" },
  { key: "travel", label: "Podróże" },
  { key: "holiday", label: "Wakacje" },
  { key: "health", label: "Zdrowie" },
  { key: "doctor", label: "Lekarz" },
  { key: "work", label: "Praca" },
  { key: "company", label: "Firma" },
  { key: "salary", label: "Pensja" },
  { key: "bills", label: "Rachunki" },
  { key: "electricity", label: "Prąd" },
  { key: "water", label: "Woda" },
  { key: "gas", label: "Gaz" },
  { key: "internet", label: "Internet" },
  { key: "phone", label: "Telefon" },
  { key: "tv", label: "Telewizja" },
  { key: "subscription", label: "Subskrypcja" },
  { key: "education", label: "Edukacja" },
  { key: "books", label: "Książki" },
  { key: "sport", label: "Sport" },
  { key: "gym", label: "Siłownia" },
  { key: "gaming", label: "Gaming" },
  { key: "entertainment", label: "Rozrywka" },
  { key: "cinema", label: "Kino" },
  { key: "music", label: "Muzyka" },
  { key: "camera", label: "Aparat" },
  { key: "microphone", label: "Mikrofon" },
  { key: "headphones", label: "Słuchawki" },
  { key: "gift", label: "Prezent" },
  { key: "clothes", label: "Ubrania" },
  { key: "beauty", label: "Uroda" },
  { key: "pets", label: "Zwierzęta" },
  { key: "child", label: "Dziecko" },
  { key: "cash", label: "Gotówka" },
  { key: "card", label: "Karta" },
  { key: "bank", label: "Bank" },
  { key: "wallet", label: "Portfel" },
  { key: "savings", label: "Oszczędności" },
  { key: "investments", label: "Inwestycje" },
  { key: "insurance", label: "Ubezpieczenie" },
  { key: "tax", label: "Podatki" },
  { key: "documents", label: "Dokumenty" },
  { key: "repair", label: "Naprawa" },
  { key: "tools", label: "Narzędzia" },
  { key: "warning", label: "Ostrzeżenie" },
  { key: "idea", label: "Pomysł" },
  { key: "heart", label: "Serce" },
  { key: "calendar", label: "Kalendarz" },
  { key: "sun", label: "Słońce" },
  { key: "more", label: "Więcej" },
  { key: "info", label: "Informacja" },
  { key: "pen", label: "Pióro" },
  { key: "keyboard", label: "Klawiatura" },
  { key: "all", label: "Wszystkie" },
  { key: "other", label: "Inne" },
  ...LETTER_ICON_OPTIONS,
] as const;

export type FinalUserIconKey = (typeof FINAL_USER_ICON_OPTIONS)[number]["key"];
type LibraryUserIconKey = Exclude<FinalUserIconKey, LetterIconKey>;
export const FINAL_USER_ICON_KEYS = FINAL_USER_ICON_OPTIONS.map(
  (icon) => icon.key,
);

export const SYSTEM_ICON_KEYS = [
  "system-dashboard",
  "system-calendar",
  "system-goals",
  "system-alert",
  "system-reminder",
  "system-payment-sources",
  "system-recurring-payments",
  "system-profile",
  "system-settings",
  "system-search",
  "system-filter",
  "system-sort",
  "system-drag-handle",
  "system-add",
  "system-edit",
  "system-delete",
  "system-copy",
  "system-save",
  "system-undo",
  "system-pin",
  "system-expand",
  "system-collapse",
  "system-close",
  "system-more",
  "system-info",
  "system-drafts",
  "system-import",
  "system-export",
  "system-trash",
  "system-lock",

  "system-records",
  "system-income",
  "system-expense",

  "income_plus",
  "expense_minus",
  "allocation",
  "lock",
  "unlock",
] as const;

export type SystemIconKey = (typeof SYSTEM_ICON_KEYS)[number];

export const COMPATIBILITY_ICON_KEYS = [
  "basket",
  "bill",
  "plus",
  "edit",
  "trash",
  "close",
  "expand",
] as const;

type CompatibilityIconKey = (typeof COMPATIBILITY_ICON_KEYS)[number];

export const LEGACY_VARIANT_ICON_KEYS = [
  "car_2",
  "car_3",
  "car_4",
  "car_5",
  "car_6",
  "plane_2",
  "plane_3",
  "plane_4",
  "plane_5",
  "plane_6",
  "holiday_2",
  "holiday_3",
  "holiday_4",
  "holiday_5",
  "holiday_6",
  "fuel_2",
  "fuel_3",
  "fuel_4",
  "fuel_5",
  "fuel_6",
  "travel_2",
  "travel_3",
  "travel_4",
  "travel_5",
  "travel_6",
] as const;

type LegacyVariantIconKey = (typeof LEGACY_VARIANT_ICON_KEYS)[number];
export type FinalIconKey =
  | FinalUserIconKey
  | SystemIconKey
  | CompatibilityIconKey
  | LegacyVariantIconKey;

const SELECTED_ICON_IDS: Record<LibraryUserIconKey | SystemIconKey, string> = {
  note: "material-symbols:note",
  exchange: "material-symbols:swap-horiz",
  home: "ph:house-fill",
  food: "material-symbols:fastfood",
  restaurant: "material-symbols:restaurant",
  coffee: "ph:coffee-fill",
  shopping: "material-symbols:shopping-cart",
  car: "ph:car-fill",
  transport: "fa6-solid:bus-simple",
  fuel: "material-symbols:local-gas-station",
  parking: "fa6-solid:square-parking",
  taxi: "ph:taxi-fill",
  plane: "fa6-solid:plane",
  travel: "fa6-solid:suitcase-rolling",
  holiday: "fa6-solid:umbrella-beach",
  health: "ph:first-aid-kit-fill",
  doctor: "ph:stethoscope-fill",
  work: "material-symbols:work",
  company: "ph:buildings-fill",
  salary: "material-symbols:payments",
  bills: "material-symbols:receipt-long",
  electricity: "material-symbols:bolt",
  water: "ph:drop-fill",
  gas: "ph:flame-fill",
  internet: "material-symbols:wifi",
  phone: "fa6-solid:mobile-screen-button",
  tv: "ph:television-fill",
  subscription: "material-symbols:subscriptions",
  education: "ph:graduation-cap-fill",
  books: "material-symbols:menu-book",
  sport: "fluent:sport-soccer-24-filled",
  gym: "material-symbols:fitness-center",
  gaming: "material-symbols:sports-esports",
  entertainment: "fa6-solid:masks-theater",
  cinema: "solar:clapperboard-play-bold",
  music: "fluent:music-note-2-24-filled",
  camera: "ph:camera-fill",
  microphone: "ph:microphone-fill",
  headphones: "material-symbols:headphones",
  gift: "fluent:gift-24-filled",
  clothes: "fa6-solid:shirt",
  beauty: "solar:magic-stick-3-bold",
  pets: "material-symbols:pets",
  child: "ph:baby-fill",
  cash: "ph:money-fill",
  card: "ph:credit-card-fill",
  bank: "material-symbols:account-balance",
  wallet: "solar:wallet-bold",
  savings: "material-symbols:savings",
  investments: "material-symbols:trending-up",
  insurance: "solar:shield-check-bold",
  tax: "fluent:receipt-money-24-filled",
  documents: "ph:files-fill",
  repair: "fa6-solid:hammer",
  tools: "ph:wrench-fill",
  warning: "ph:warning-fill",
  idea: "fa6-solid:lightbulb",
  heart: "ph:heart-fill",
  calendar: "ph:calendar-fill",
  sun: "ph:sun-fill",
  more: "material-symbols:more-horiz",
  info: "ph:info-fill",
  pen: "fluent:pen-24-filled",
  keyboard: "fa6-solid:keyboard",
  all: "material-symbols:all-inclusive",
  other: "material-symbols:category",
  "system-dashboard": "ph:squares-four-fill",
  "system-calendar": "ph:calendar-fill",
  "system-goals": "ph:target-fill",
  "system-alert": "ph:warning-fill",
  "system-reminder": "fluent:alert-24-filled",
  "system-payment-sources": "solar:wallet-money-bold",
  "system-recurring-payments": "ph:arrows-clockwise-fill",
  "system-profile": "material-symbols:account-circle",
  "system-settings": "fluent:settings-24-filled",
  "system-search": "material-symbols:search",
  "system-filter": "material-symbols:filter-alt",
  "system-sort": "fluent:arrow-sort-24-filled",
  "system-drag-handle": "material-symbols:drag-indicator",
  "system-add": "ph:plus-circle-fill",
  "system-edit": "fluent:edit-24-filled",
  "system-delete": "fa6-solid:trash-can",
  "system-copy": "ph:copy-fill",
  "system-save": "material-symbols:save",
  "system-undo": "material-symbols:undo",
  "system-pin": "ph:push-pin-fill",
  "system-expand": "material-symbols:expand-more",
  "system-collapse": "material-symbols:expand-less",
  "system-close": "material-symbols:close",
  "system-more": "material-symbols:more-horiz",
  "system-info": "ph:info-fill",
  "system-drafts": "material-symbols:drafts",
  "system-import": "fluent:arrow-download-24-filled",
  "system-export": "fluent:arrow-upload-24-filled",
  "system-trash": "fa6-solid:trash-can",
  "system-lock": "material-symbols:lock",

  "system-records": "material-symbols:receipt-long",
  "system-income": "material-symbols:north-east",
  "system-expense": "material-symbols:south-west",

  income_plus: "fa6-solid:circle-plus",
  expense_minus: "fa6-solid:circle-minus",
  allocation: "material-symbols:tune",
  lock: "fluent:lock-closed-24-filled",
  unlock: "fluent:lock-open-24-filled",
};

const COMPATIBILITY_TARGETS: Record<
  CompatibilityIconKey | LegacyVariantIconKey,
  LibraryUserIconKey | SystemIconKey
> = {
  basket: "shopping",
  bill: "bills",
  plus: "system-add",
  edit: "system-edit",
  trash: "system-trash",
  close: "system-close",
  expand: "system-expand",
  car_2: "car",
  car_3: "car",
  car_4: "car",
  car_5: "car",
  car_6: "car",
  plane_2: "plane",
  plane_3: "plane",
  plane_4: "plane",
  plane_5: "plane",
  plane_6: "plane",
  holiday_2: "holiday",
  holiday_3: "holiday",
  holiday_4: "holiday",
  holiday_5: "holiday",
  holiday_6: "holiday",
  fuel_2: "fuel",
  fuel_3: "fuel",
  fuel_4: "fuel",
  fuel_5: "fuel",
  fuel_6: "fuel",
  travel_2: "travel",
  travel_3: "travel",
  travel_4: "travel",
  travel_5: "travel",
  travel_6: "travel",
};

export const FINAL_ICON_IDS: Record<
  Exclude<FinalIconKey, LetterIconKey>,
  string
> = {
  ...SELECTED_ICON_IDS,
  ...(Object.fromEntries(
    Object.entries(COMPATIBILITY_TARGETS).map(([alias, target]) => [
      alias,
      SELECTED_ICON_IDS[target],
    ]),
  ) as Record<CompatibilityIconKey | LegacyVariantIconKey, string>),
};

export const isFinalIconKey = (value?: string | null): value is FinalIconKey =>
  Boolean(
    value &&
    (LETTER_ICON_OPTIONS.some((option) => option.key === value) ||
      Object.prototype.hasOwnProperty.call(FINAL_ICON_IDS, value)),
  );

export const getFinalIconId = (key?: string | null) =>
  key && Object.prototype.hasOwnProperty.call(FINAL_ICON_IDS, key)
    ? FINAL_ICON_IDS[key as Exclude<FinalIconKey, LetterIconKey>]
    : null;

export const getLetterIconCharacter = (
  key?: string | null,
): LetterIconCharacter | null =>
  LETTER_ICON_OPTIONS.find((option) => option.key === key)?.character || null;
