export const uiZIndex = {
  // Semantic layers for new UI foundation work.
  base: 0,
  raised: 1,
  sticky: 40,
  dropdown: 1200,
  popover: 2200,
  panel: 2600,
  drawer: 2600,
  modal: 3000,
  toast: 12000,
  criticalOverlay: 130000,

  // Legacy bridge aliases. Keep values stable until the owning module migrates.
  floatingAction: 950,
  modalBase: 1000,
  modalRaised: 1001,
  modalPrompt: 1100,
  dropdownRaised: 1201,
  sidebar: 900,
  dashboardOverlay: 1200,
  mobileDrawer: 1300,
  dashboardAddPanel: 1450,
  floatingMenu: 1600,
  floatingMenuBase: 1700,
  floatingMenuElevated: 1800,
  sidebarPanel: 2300,
  mobilePanel: 2400,
  sidePanelOverlay: 2600,
  sidePanel: 2610,
  sidePanelDropdown: 2700,
  mobilePopover: 3100,
  mobileCritical: 3200,
  rightRailDropdown: 3600,
  profileMenu: 4200,
  workspacePopover: 5000,
  widgetDropdown: 20,
  widgetConfig: 12,
  widgetControl: 4,
  widgetHeader: 5,
  widgetConfigOpen: 7,
  widgetOverlay: 8,
  creatorDropdown: 30,
  localBase: 0,
  localRaised: 1,
  localOverlay: 2,
  localAbove: 3,
  localControl: 4,
  localHeader: 5,
  localActive: 10,
  localEmergency: 42,
  mobileCategoryMenu: 760,
  categoryPopover: 20000,
  categoryPopoverElevated: 20010,
  categoryAutocomplete: 20020,
  categoryOverlay: 22000,
  topbar: 90000,
  topbarDropdown: 90020,
  topbarOverlay: 120000,
  topbarOverlayRaised: 120001,
  topbarCritical: 120010,
  globalCritical: 130000,
} as const

export const uiColorTokens = {
  primaryNavy: '#082C7A',
  primaryBlue: '#215DFF',
  softBlue: '#EAF1FF',
  lightBlueBorder: '#D6E4FF',
  extraLightBlue: '#F7FAFF',
  primaryText: '#13203A',
  secondaryText: '#5F6B85',
  mutedText: '#98A2B3',
  whiteText: '#FFFFFF',
  mainBackground: '#F8FAFD',
  cardBackground: '#FFFFFF',
  softSectionBackground: '#F4F7FC',
  hoverBackground: '#F2F6FF',
  primaryBorder: '#215DFF',
  softBorder: '#DCE6F7',
  dividerBorder: '#E8EEF8',
  disabledBorder: '#E2E8F3',
  income: '#11884F',
  incomeSoft: '#E9F8F1',
  expense: '#D7263D',
  expenseSoft: '#FFF1F2',
  balancePositive: '#11884F',
  balanceNegative: '#D7263D',
  limitWarning: '#F59E0B',
  limitExceeded: '#D7263D',
  success: '#1FA971',
  successSoft: '#E9F8F1',
  error: '#E5484D',
  errorSoft: '#FFF1F2',
  warning: '#F59E0B',
  warningSoft: '#FFF7E8',
  shadowLight: 'rgba(15,23,42,0.04)',
  shadowMedium: 'rgba(15,23,42,0.08)',
  shadowStrong: 'rgba(15,23,42,0.14)',
  softBlueGradient: 'linear-gradient(180deg,#FFFFFF 0%,#F7FAFF 100%)',
  incomeGradient: 'linear-gradient(180deg,#F2FFF8 0%,#E7F9EF 100%)',
  expenseGradient: 'linear-gradient(180deg,#FFF6F6 0%,#FFF0F0 100%)',
} as const

export const uiPrimitiveContracts = {
  button: ['hero', 'standard', 'utility', 'icon'],
  buttonState: ['active'],
  buttonTone: ['default', 'danger', 'success'],
  buttonWidth: ['auto', 'equal', 'full'],
  buttonDensity: ['compact', 'normal'],
  iconButton: ['default', 'subtle', 'danger', 'active'],
  input: ['default', 'small', 'invalid', 'disabled'],
  select: ['default', 'small', 'invalid', 'disabled'],
  checkbox: ['default', 'disabled'],
  badge: ['neutral', 'info', 'success', 'warning', 'danger'],
  tag: ['default', 'interactive', 'removable'],
  segmentedControl: ['default', 'compact'],
  card: ['default', 'elevated', 'interactive'],
  panel: ['workspace', 'utility', 'side', 'rail'],
  modal: ['s', 'm', 'l', 'xl'],
  overlay: ['popover', 'drawer', 'workspace'],
  dropdown: ['menu', 'autocomplete', 'topbar'],
  toolbar: ['default', 'compact', 'sticky'],
} as const

export const uiSurfacePrimitives = {
  card: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-card-radius)',
    background: 'var(--ui-surface-card)',
    shadow: 'var(--ui-shadow-card)',
    padding: 'var(--ui-surface-card-padding)',
  },
  panel: {
    border: '1px solid var(--ui-color-border)',
    radius: 'var(--ui-panel-radius)',
    background: 'var(--ui-surface-workspace)',
    shadow: 'var(--ui-shadow-panel)',
    padding: 'var(--ui-surface-panel-padding)',
  },
  utilityPanel: {
    border: '1px solid var(--ui-color-border)',
    radius: 'var(--ui-panel-radius)',
    background: 'var(--ui-surface-rail)',
    shadow: 'var(--ui-shadow-panel)',
    padding: 'var(--ui-surface-panel-padding)',
  },
  modalSurface: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-modal-radius)',
    background: 'var(--ui-surface-modal)',
    shadow: 'var(--ui-shadow-modal)',
    padding: 'var(--ui-surface-modal-padding)',
  },
  modalSurfaceNeutral: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-modal-radius)',
    background: 'var(--ui-surface-modal)',
    shadow: 'var(--ui-overlay-modal-shadow-neutral)',
    padding: 'var(--ui-surface-modal-padding)',
  },
  modalSurfacePrompt: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-modal-radius)',
    background: 'var(--ui-surface-modal)',
    shadow: 'var(--ui-surface-modal-shadow-prompt)',
    padding: 'var(--ui-surface-modal-padding)',
  },
  modalSurfaceStrong: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-modal-radius)',
    background: 'var(--ui-surface-modal)',
    shadow: 'var(--ui-overlay-modal-shadow-strong)',
    padding: 'var(--ui-surface-modal-padding-compact)',
  },
  modalSurfaceInfoBorder: {
    border: '1px solid var(--ui-surface-border-info)',
    radius: 'var(--ui-modal-radius)',
    background: 'var(--ui-surface-modal)',
    shadow: 'var(--ui-shadow-modal)',
    padding: 'var(--ui-surface-modal-padding)',
  },
  dropdownSurface: {
    border: '1px solid var(--ui-surface-border-control)',
    radius: 'var(--ui-dropdown-radius)',
    background: 'var(--ui-surface-dropdown)',
    shadow: 'var(--ui-overlay-dropdown-shadow-tight)',
    padding: 'var(--ui-surface-dropdown-padding)',
  },
  profileDropdownSurface: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-radius-sm)',
    background: 'var(--ui-surface-dropdown)',
    shadow: 'var(--ui-shadow-dropdown)',
    padding: 'var(--ui-surface-dropdown-padding)',
  },
  popoverSurface: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-radius-sm)',
    background: 'var(--ui-surface-dropdown)',
    shadow: 'var(--ui-shadow-dropdown)',
    padding: 'var(--ui-surface-popover-padding)',
  },
  widgetSurface: {
    border: '1px solid var(--ui-color-border)',
    radius: 'var(--ui-card-radius)',
    background: 'var(--ui-surface-widget)',
    shadow: 'var(--ui-shadow-card)',
    padding: 'var(--ui-surface-card-padding)',
  },
  emptyState: {
    border: '1px dashed var(--ui-surface-empty-border)',
    radius: 'var(--ui-panel-radius)',
    background: 'rgba(255, 255, 255, 0.42)',
    padding: 'var(--ui-surface-empty-padding)',
  },
  infoBox: {
    border: '1px solid var(--ui-surface-border-default)',
    radius: 'var(--ui-radius-lg)',
    background: 'var(--ui-surface-info)',
    padding: 'var(--ui-surface-card-padding)',
  },
  statusBox: {
    danger: {
      border: '1px solid var(--ui-surface-border-danger)',
      radius: 'var(--ui-surface-status-radius)',
      background: 'var(--ui-surface-status-danger)',
      padding: 'var(--ui-surface-status-padding)',
    },
  },
} as const

export const uiLayoutPrimitives = {
  appShell: {
    leftWidth: 'var(--ui-shell-left-width)',
    rightRailWidth: 'var(--ui-shell-right-rail-width)',
    topHeight: 'var(--ui-shell-top-height)',
    gap: 'var(--ui-shell-gap)',
    radius: 'var(--ui-shell-radius)',
    contentLayer: uiZIndex.localRaised,
  },
  topbar: {
    layer: uiZIndex.topbar,
    overlayLayer: uiZIndex.topbarOverlay,
    insetY: 'var(--ui-topbar-inset-y)',
    insetX: 'var(--ui-topbar-inset-x)',
    radius: 'var(--ui-topbar-radius)',
    gap: 'var(--ui-topbar-gap)',
    minHeight: 'var(--ui-topbar-min-height)',
  },
  leftSidebar: {
    layer: uiZIndex.sidebar,
    width: 'var(--ui-left-sidebar-width)',
    radius: 'var(--ui-left-sidebar-radius)',
    padding: 'var(--ui-left-sidebar-padding)',
  },
  rightRail: {
    layer: uiZIndex.dashboardOverlay,
    width: 'var(--ui-right-rail-width)',
    maxWidth: 'var(--ui-right-rail-content-max-width)',
    stickyTop: 'var(--ui-right-rail-sticky-top)',
  },
  workspace: {
    layer: uiZIndex.localRaised,
    railWidth: 'var(--ui-shell-workspace-rail-width)',
    gap: 'var(--ui-shell-gap)',
  },
  sidePanel: {
    layer: uiZIndex.sidePanel,
    overlayLayer: uiZIndex.sidePanelOverlay,
    left: 'var(--ui-side-panel-left)',
    top: 'var(--ui-side-panel-top)',
    width: 'var(--ui-side-panel-width)',
    radius: 'var(--ui-side-panel-radius)',
  },
  drawer: {
    layer: uiZIndex.sidebarPanel,
    left: 'var(--ui-drawer-left)',
    top: 'var(--ui-drawer-top)',
    width: 'var(--ui-drawer-width)',
  },
  floatingLayer: {
    layer: uiZIndex.floatingAction,
  },
} as const

export const uiButtonApi = {
  classNames: {
    hero: 'ui-button--hero',
    standard: 'ui-button--standard',
    utility: 'ui-button--utility',
    icon: 'ui-button--icon',
  },
  attributes: {
    state: 'data-button-state',
    tone: 'data-button-tone',
    width: 'data-button-width',
    density: 'data-button-density',
  },
  legacyClassNames: {
    primary: 'ui-button-primary',
    secondary: 'ui-button-secondary',
    danger: 'ui-button-danger',
    hero: 'ui-button-hero',
    standard: 'ui-button-standard',
    utility: 'ui-button-utility',
    icon: 'ui-button-icon',
  },
} as const

export const uiModalApi = {
  classNames: {
    backdrop: 'ui-overlay-backdrop',
    modal: 'ui-modal',
    modalS: 'ui-modal--s',
    modalM: 'ui-modal--m',
    modalL: 'ui-modal--l',
    modalXl: 'ui-modal--xl',
    header: 'ui-modal__header',
    body: 'ui-modal__body',
    footer: 'ui-modal__footer',
    close: 'ui-modal__close',
    popover: 'ui-popover',
    drawer: 'ui-drawer',
    workspaceOverlay: 'ui-workspace-overlay',
  },
  attributes: {
    backdrop: 'data-overlay-backdrop',
    size: 'data-modal-size',
    layer: 'data-overlay-layer',
    closeArea: 'data-modal-close-area',
  },
  backdrop: {
    soft: 'soft',
    standard: 'standard',
    strong: 'strong',
  },
} as const

export const uiControlPrimitives = {
  button: {
    hero: {
      className: uiButtonApi.classNames.hero,
      minHeight: 'var(--ui-button-height-hero)',
      radius: 'var(--ui-button-radius)',
      padding: 'var(--ui-button-padding-hero)',
      border: '2px solid var(--ui-button-border-strong)',
      background: 'var(--ui-button-bg)',
      color: 'var(--ui-button-text-strong)',
      fontWeight: 'var(--ui-button-font-weight-hero)',
      cursor: 'pointer',
    },
    standard: {
      className: uiButtonApi.classNames.standard,
      minHeight: 'var(--ui-button-height-standard)',
      radius: 'var(--ui-button-radius)',
      padding: 'var(--ui-button-padding-standard)',
      border: '1px solid var(--ui-button-border-strong)',
      background: 'var(--ui-button-bg)',
      color: 'var(--ui-button-text)',
      fontWeight: 'var(--ui-button-font-weight-standard)',
      cursor: 'pointer',
    },
    utility: {
      className: uiButtonApi.classNames.utility,
      minHeight: 'var(--ui-button-height-utility)',
      radius: 'var(--ui-button-radius)',
      padding: 'var(--ui-button-padding-utility)',
      border: '1px solid var(--ui-button-border)',
      background: 'var(--ui-button-bg)',
      color: 'var(--ui-button-text)',
      fontWeight: 'var(--ui-button-font-weight-utility)',
      cursor: 'pointer',
    },
    icon: {
      className: uiButtonApi.classNames.icon,
      width: 'var(--ui-button-height-icon)',
      minWidth: 'var(--ui-button-height-icon)',
      height: 'var(--ui-button-height-icon)',
      minHeight: 'var(--ui-button-height-icon)',
      radius: 'var(--ui-button-radius)',
      padding: 0,
      border: '1px solid var(--ui-button-border)',
      background: 'var(--ui-button-bg-tint)',
      color: 'var(--ui-button-text)',
      cursor: 'pointer',
    },
    primary: {
      className: uiButtonApi.legacyClassNames.primary,
      mapsTo: uiButtonApi.classNames.standard,
      minHeight: 'var(--ui-button-height-standard)',
      radius: 'var(--ui-button-radius)',
      padding: 'var(--ui-button-padding-standard)',
      border: '1px solid var(--ui-button-border-strong)',
      background: 'var(--ui-button-bg)',
      color: 'var(--ui-button-text-strong)',
      fontWeight: 'var(--ui-button-font-weight-standard)',
      cursor: 'pointer',
    },
    secondary: {
      className: uiButtonApi.legacyClassNames.secondary,
      mapsTo: uiButtonApi.classNames.utility,
      minHeight: 'var(--ui-button-height-utility)',
      radius: 'var(--ui-button-radius)',
      padding: 'var(--ui-button-padding-utility)',
      border: '1px solid var(--ui-button-border)',
      background: 'var(--ui-button-bg)',
      color: 'var(--ui-button-text)',
      fontWeight: 'var(--ui-button-font-weight-utility)',
      cursor: 'pointer',
    },
    danger: {
      className: uiButtonApi.legacyClassNames.danger,
      mapsTo: uiButtonApi.classNames.utility,
      tone: 'danger',
      minHeight: 'var(--ui-button-height-utility)',
      radius: 'var(--ui-button-radius)',
      padding: 'var(--ui-button-padding-utility)',
      border: '1px solid var(--ui-button-border)',
      background: 'var(--ui-button-bg)',
      color: 'var(--ui-color-expense)',
      fontWeight: 'var(--ui-button-font-weight-utility)',
      cursor: 'pointer',
    },
    menuItem: {
      padding: 'var(--ui-button-menu-padding)',
      radius: 'var(--ui-radius-none)',
      fontSize: 'var(--ui-font-size-body)',
      cursor: 'pointer',
    },
    profileMenuItem: {
      padding: 'var(--ui-button-profile-menu-padding)',
      radius: 'var(--ui-space-3)',
      cursor: 'pointer',
    },
  },
  iconButton: {
    default: {
      radius: 'var(--ui-button-radius)',
      cursor: 'pointer',
    },
    avatar: {
      radius: '50%',
      cursor: 'pointer',
    },
  },
  input: {
    modal: {
      height: 'var(--ui-input-height-lg)',
      radius: 'var(--ui-input-radius)',
      padding: 'var(--ui-input-padding-md)',
      border: '1px solid var(--ui-color-control-border)',
      background: 'var(--ui-color-card-background)',
      color: 'var(--ui-color-control-text)',
      fontSize: 'var(--ui-font-size-body)',
      outline: 'none',
    },
  },
  select: {
    modal: {
      height: 'var(--ui-select-height-lg)',
      radius: 'var(--ui-input-radius)',
      padding: 'var(--ui-input-padding-md)',
      border: '1px solid var(--ui-color-control-border)',
      background: 'var(--ui-color-card-background)',
      color: 'var(--ui-color-control-text)',
      fontSize: 'var(--ui-font-size-body)',
      outline: 'none',
    },
  },
  checkbox: {
    default: {
      gap: 'var(--ui-checkbox-gap)',
    },
  },
  badge: {
    danger: {
      minWidth: 'var(--ui-badge-min-width-sm)',
      height: 'var(--ui-badge-height-sm)',
      radius: 'var(--ui-badge-radius)',
      background: 'var(--ui-color-expense)',
      color: 'var(--ui-color-white-text)',
    },
  },
  tag: {
    default: {
      radius: 'var(--ui-radius-pill)',
      padding: 'var(--ui-space-2) var(--ui-space-4)',
    },
  },
  segmentedControl: {
    default: {
      gap: 'var(--ui-space-2)',
      padding: 'var(--ui-space-2)',
      radius: 'var(--ui-radius-pill)',
    },
  },
} as const

const uiFloatingLayerOverlayContract = {
  layer: uiZIndex.floatingAction,
  radius: 'var(--ui-radius-pill)',
  shadow: 'var(--ui-shadow-floating)',
  ownsFocus: false,
  dismissesOnOutsidePointer: false,
} as const

export const uiBackdropPrimitives = {
  soft: {
    className: uiModalApi.classNames.backdrop,
    tone: uiModalApi.backdrop.soft,
    background: 'var(--ui-overlay-backdrop-soft)',
    blur: 'var(--ui-overlay-backdrop-blur-soft)',
  },
  standard: {
    className: uiModalApi.classNames.backdrop,
    tone: uiModalApi.backdrop.standard,
    background: 'var(--ui-overlay-backdrop)',
    blur: 'var(--ui-overlay-backdrop-blur-standard)',
  },
  strong: {
    className: uiModalApi.classNames.backdrop,
    tone: uiModalApi.backdrop.strong,
    background: 'var(--ui-overlay-backdrop-strong)',
    blur: 'var(--ui-overlay-backdrop-blur-strong)',
  },
} as const

export const uiModalSizePrimitives = {
  s: {
    className: uiModalApi.classNames.modalS,
    width: 'var(--ui-modal-width-s)',
    maxWidth: 'var(--ui-modal-max-width-s)',
    maxHeight: 'var(--ui-modal-max-height-s)',
  },
  m: {
    className: uiModalApi.classNames.modalM,
    width: 'var(--ui-modal-width-m)',
    maxWidth: 'var(--ui-modal-max-width-m)',
    maxHeight: 'var(--ui-modal-max-height-m)',
  },
  l: {
    className: uiModalApi.classNames.modalL,
    width: 'var(--ui-modal-width-l)',
    maxWidth: 'var(--ui-modal-max-width-l)',
    maxHeight: 'var(--ui-modal-max-height-l)',
  },
  xl: {
    className: uiModalApi.classNames.modalXl,
    width: 'var(--ui-modal-width-xl)',
    maxWidth: 'var(--ui-modal-max-width-xl)',
    maxHeight: 'var(--ui-modal-max-height-xl)',
  },
} as const

export const uiOverlayContracts = {
  modal: {
    className: uiModalApi.classNames.modal,
    layer: uiZIndex.modal,
    width: '100%',
    maxWidth: 'var(--ui-modal-max-width-m)',
    maxHeight: 'var(--ui-modal-max-height-m)',
    radius: 'var(--ui-modal-radius)',
    shadow: 'var(--ui-shadow-modal)',
    padding: 'var(--ui-overlay-modal-padding)',
    backdrop: 'var(--ui-overlay-backdrop)',
    bodyOverflow: 'var(--ui-modal-body-overflow)',
    headerPadding: 'var(--ui-modal-header-padding)',
    bodyPadding: 'var(--ui-modal-body-padding)',
    footerPadding: 'var(--ui-modal-footer-padding)',
    closeArea: 'var(--ui-modal-close-area)',
    ownsFocus: true,
    dismissesOnBackdrop: true,
  },
  dropdown: {
    layer: uiZIndex.dropdown,
    radius: 'var(--ui-dropdown-radius)',
    shadow: 'var(--ui-shadow-dropdown)',
    padding: 'var(--ui-overlay-dropdown-padding)',
    ownsFocus: false,
    dismissesOnOutsidePointer: true,
  },
  popover: {
    className: uiModalApi.classNames.popover,
    layer: uiZIndex.popover,
    width: 'var(--ui-popover-width)',
    minWidth: 'var(--ui-popover-min-width)',
    maxWidth: 'var(--ui-popover-max-width)',
    maxHeight: 'var(--ui-popover-max-height)',
    radius: 'var(--ui-radius-sm)',
    shadow: 'var(--ui-shadow-popover)',
    padding: 'var(--ui-overlay-popover-padding)',
    bodyOverflow: 'var(--ui-popover-body-overflow)',
    ownsFocus: false,
    dismissesOnOutsidePointer: true,
  },
  sidePanel: {
    layer: uiZIndex.sidePanel,
    backdropLayer: uiZIndex.sidePanelOverlay,
    radius: 'var(--ui-panel-radius)',
    shadow: 'var(--ui-shadow-panel)',
    ownsFocus: false,
    dismissesOnBackdrop: true,
  },
  drawer: {
    className: uiModalApi.classNames.drawer,
    layer: uiZIndex.drawer,
    width: 'var(--ui-drawer-panel-width)',
    maxWidth: 'var(--ui-drawer-panel-max-width)',
    maxHeight: 'var(--ui-drawer-panel-max-height)',
    radius: 'var(--ui-panel-radius)',
    shadow: 'var(--ui-shadow-panel)',
    padding: 'var(--ui-overlay-drawer-padding)',
    bodyOverflow: 'var(--ui-drawer-panel-body-overflow)',
    ownsFocus: true,
    dismissesOnBackdrop: true,
  },
  workspaceOverlay: {
    className: uiModalApi.classNames.workspaceOverlay,
    layer: uiZIndex.panel,
    width: 'var(--ui-workspace-overlay-width)',
    maxWidth: 'var(--ui-workspace-overlay-max-width)',
    maxHeight: 'var(--ui-workspace-overlay-max-height)',
    radius: 'var(--ui-panel-radius)',
    shadow: 'var(--ui-shadow-panel)',
    padding: 'var(--ui-overlay-workspace-padding)',
    bodyOverflow: 'var(--ui-workspace-overlay-body-overflow)',
    ownsFocus: true,
    dismissesOnBackdrop: true,
  },
  toast: {
    layer: uiZIndex.toast,
    radius: 'var(--ui-radius-xl)',
    shadow: 'var(--ui-shadow-popover)',
    ownsFocus: false,
    dismissesOnOutsidePointer: false,
  },
  tooltip: {
    layer: uiZIndex.popover,
    radius: 'var(--ui-radius-sm)',
    shadow: 'var(--ui-shadow-subtle)',
    ownsFocus: false,
    dismissesOnOutsidePointer: false,
  },
  floatingLayer: uiFloatingLayerOverlayContract,
  floatingActions: uiFloatingLayerOverlayContract,
} as const

export const uiOverlayPrimitives = {
  modal: uiOverlayContracts.modal,
  modalS: {
    ...uiOverlayContracts.modal,
    ...uiModalSizePrimitives.s,
  },
  modalM: {
    ...uiOverlayContracts.modal,
    ...uiModalSizePrimitives.m,
  },
  modalL: {
    ...uiOverlayContracts.modal,
    ...uiModalSizePrimitives.l,
  },
  modalXl: {
    ...uiOverlayContracts.modal,
    ...uiModalSizePrimitives.xl,
  },
  modalBase: {
    ...uiOverlayContracts.modal,
    layer: uiZIndex.modalBase,
  },
  modalRaised: {
    ...uiOverlayContracts.modal,
    layer: uiZIndex.modalRaised,
  },
  modalPrompt: {
    ...uiOverlayContracts.modal,
    layer: uiZIndex.modalPrompt,
    backdrop: 'var(--ui-overlay-backdrop-prompt)',
  },
  dropdown: uiOverlayContracts.dropdown,
  dropdownRaised: {
    ...uiOverlayContracts.dropdown,
    layer: uiZIndex.dropdownRaised,
    shadow: 'var(--ui-overlay-dropdown-shadow-tight)',
  },
  profileDropdown: {
    ...uiOverlayContracts.dropdown,
    layer: uiZIndex.profileMenu,
    radius: 'var(--ui-radius-sm)',
  },
  popover: uiOverlayContracts.popover,
  inlinePopover: {
    ...uiOverlayContracts.popover,
    layer: uiZIndex.sticky,
    shadow: 'var(--ui-shadow-dropdown)',
  },
  drawer: uiOverlayContracts.drawer,
  sidePanel: uiOverlayContracts.sidePanel,
  workspaceOverlay: uiOverlayContracts.workspaceOverlay,
  backdropSoft: uiBackdropPrimitives.soft,
  backdropStandard: uiBackdropPrimitives.standard,
  backdropStrong: uiBackdropPrimitives.strong,
  toast: uiOverlayContracts.toast,
  floatingLayer: uiOverlayContracts.floatingLayer,
  floatingActions: uiOverlayContracts.floatingActions,
} as const

export type UiZIndexToken = keyof typeof uiZIndex
export type UiLayoutPrimitive = keyof typeof uiLayoutPrimitives
export type UiModalSize = keyof typeof uiModalSizePrimitives
export type UiBackdropTone = keyof typeof uiBackdropPrimitives
export type UiOverlayKind = keyof typeof uiOverlayContracts
export type UiOverlayPrimitive = keyof typeof uiOverlayPrimitives
