'use client'

import { useMemo, useState } from 'react'
import type { Category, PaymentSource, Transaction } from '../../lib/budgetPageTypes'
import type { AmountMismatchDecision, OverpaymentDecision, SkippedInstallmentPolicy } from '../../lib/recurring-payments/actionPolicies'
import type { RecurringOccurrenceRow, RecurringPlanDraft, RecurringPlanRow } from '../../lib/recurring-payments/data'
import { useRecurringPaymentsData } from '../../lib/recurring-payments/useRecurringPaymentsData'
import { buildRecurringPaymentCardViewModel, buildRecurringPaymentCreatorViewModel, buildRecurringPaymentDetailsViewModel } from '../../lib/recurring-payments/viewModels'
import { PrimaryAction, SecondaryAction } from '../ui/FoundationPrimitives'
import RecurringPaymentPlanForm from './RecurringPaymentPlanForm'

type Props={profileId:string;categoriesById:Record<string,Category>;categoryOptions:Category[];paymentSources:PaymentSource[];transactions:Transaction[];onAddEntry:(plan:RecurringPlanRow,occurrence:RecurringOccurrenceRow)=>void}
type DecisionState={kind:'skip';occurrence:RecurringOccurrenceRow}|{kind:'amount';occurrence:RecurringOccurrenceRow;actualAmount:number;overpayment:boolean}

export default function RecurringPaymentsStage2Panel({profileId,categoriesById,categoryOptions,paymentSources,transactions,onAddEntry}:Props){
 const data=useRecurringPaymentsData(profileId);const [selectedId,setSelectedId]=useState<string|null>(null);const [draft,setDraft]=useState<RecurringPlanDraft|null>(null);const [busy,setBusy]=useState(false);const [decision,setDecision]=useState<DecisionState|null>(null);const [notice,setNotice]=useState('');const today=new Date().toISOString().slice(0,10)
 const selected=data.plans.find(p=>p.id===selectedId)||null;const selectedOccurrences=data.occurrences.filter(o=>o.plan_id===selectedId)
 const cards=useMemo(()=>data.plans.map(p=>buildRecurringPaymentCardViewModel(p,data.occurrences.filter(o=>o.plan_id===p.id),today)),[data.plans,data.occurrences,today])
 const save=async()=>{if(!draft||!draft.name.trim()||!draft.category_id)return;setBusy(true);try{await (draft.id?data.updatePlan(draft):data.createPlan(draft));setDraft(null)}finally{setBusy(false)}}
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn()}catch(error){setNotice(error instanceof Error?error.message:'Operacja nie powiodła się')}finally{setBusy(false)}}
 const chooseSkip=async(policy:SkippedInstallmentPolicy)=>{if(!decision||decision.kind!=='skip')return;if(policy==='manual_schedule'){setNotice('Ręczny edytor harmonogramu jest backlogiem; intencja została zachowana w kontrakcie UI.');setDecision(null);return}await act(async()=>{await data.skip(decision.occurrence.id);await data.applyDecision(decision.occurrence.id,{kind:'skip',decision:policy})});setDecision(null)}
 const chooseAmount=async(choice:AmountMismatchDecision|OverpaymentDecision)=>{if(!decision||decision.kind!=='amount')return;if(choice==='edit_schedule_manually'||choice==='manual_schedule'||choice==='shorten_schedule'){setNotice('Ta decyzja prowadzi do ręcznego/zaawansowanego edytora harmonogramu — backlog.');setDecision(null);return}await act(()=>data.applyDecision(decision.occurrence.id,decision.overpayment?{kind:'overpayment',decision:choice as OverpaymentDecision,actualAmount:decision.actualAmount}:{kind:'amount_mismatch',decision:choice as AmountMismatchDecision,actualAmount:decision.actualAmount}));setDecision(null)}
 const link=async(occurrence:RecurringOccurrenceRow,transaction:Transaction)=>{await act(()=>data.linkTransaction(occurrence.id,transaction.id));const actual=Number(transaction.amount);if(occurrence.planned_amount!==null&&Math.abs(actual-occurrence.planned_amount)>=0.01)setDecision({kind:'amount',occurrence,actualAmount:actual,overpayment:actual>occurrence.planned_amount})}
 if(data.error)return <div data-ui-empty-state="true">Etap 2.5 wymaga zastosowania migracji SQL. {data.error}</div>
 if(draft)return <RecurringPaymentPlanForm draft={draft} setDraft={setDraft} categories={categoryOptions} sources={paymentSources} busy={busy} onSave={()=>void save()} onCancel={()=>setDraft(null)}/>
 if(selected){const vm=buildRecurringPaymentDetailsViewModel({plan:selected,occurrences:selectedOccurrences,categories:categoriesById,sources:paymentSources,transactions,links:data.links,history:data.history,today});return <section data-recurring-stage2="details"><SecondaryAction onClick={()=>setSelectedId(null)}>Wróć do listy</SecondaryAction><h3>{vm.title}</h3><p>{vm.typeLabel} · {vm.categoryLabel} · {vm.paymentSourceLabel}</p><p>Najbliższe: {vm.nextOccurrence?.due_date||'brak'} · zaległe: {vm.overdueOccurrences.length}</p><p>Postęp: {vm.progress?`${vm.progress.completed}/${vm.progress.total} (${vm.progress.percent}%)`:'plan bez końcowej liczby rat'} · wykonane: {vm.statistics.completed} · pominięte: {vm.statistics.skipped} · plan: {vm.statistics.plannedTotal.toFixed(2)} · realnie: {vm.statistics.actualTotal.toFixed(2)}</p><PrimaryAction onClick={()=>setDraft(buildRecurringPaymentCreatorViewModel(selected,data.installmentTerms.find(t=>t.plan_id===selected.id),data.loanTerms.find(t=>t.plan_id===selected.id)).draft)}>Edytuj</PrimaryAction>{notice&&<p role="status">{notice}</p>}
 {decision?.kind==='skip'&&<div role="dialog"><strong>Co zrobić z pominiętą ratą?</strong><button onClick={()=>void chooseSkip('append_at_end')}>Dodaj ratę na koniec</button><button onClick={()=>void chooseSkip('keep_schedule')}>Zostaw harmonogram</button><button onClick={()=>void chooseSkip('manual_schedule')}>Edytuj ręcznie</button></div>}
 {decision?.kind==='amount'&&<div role="dialog"><strong>{decision.overpayment?'Jak rozliczyć nadpłatę?':'Kwota różni się od planowanej'}</strong><button onClick={()=>void chooseAmount('this_occurrence_only')}>Tylko to wystąpienie</button>{decision.overpayment?<><button onClick={()=>void chooseAmount('shorten_schedule')}>Skróć harmonogram</button><button onClick={()=>void chooseAmount('reduce_future_installments')}>Zmniejsz przyszłe raty</button><button onClick={()=>void chooseAmount('manual_schedule')}>Edytuj ręcznie</button></>:<><button onClick={()=>void chooseAmount('change_from_next_occurrence')}>Zmień od następnego</button><button onClick={()=>void chooseAmount('edit_schedule_manually')}>Edytuj harmonogram ręcznie</button></>}</div>}
 <h4>Wystąpienia</h4>{vm.occurrences.length===0?<p>Brak wygenerowanych wystąpień.</p>:vm.occurrences.map(o=><article key={o.id} data-ui-card="true"><strong>{o.due_date}</strong> · plan: {o.amountLabel} · realnie: {o.actualAmountLabel} · {o.stateLabel}{o.status==='skipped'&&' · pominięte'}{o.status==='completed_without_transaction'&&' · wykonane bez wpisu'}{o.linkedTransactions.map(t=><div key={t.id}>Wpis: {t.description||t.date} ({Number(t.amount).toFixed(2)})</div>)}{o.linkedTransactions.length>0&&o.planned_amount!==null&&Math.abs(o.actualAmount-o.planned_amount)>=0.01&&<button type="button" onClick={()=>setDecision({kind:'amount',occurrence:o,actualAmount:o.actualAmount,overpayment:o.actualAmount>o.planned_amount!})}>Rozstrzygnij różnicę kwoty</button>}<div>{o.status==='pending'&&<><PrimaryAction disabled={busy} onClick={()=>onAddEntry(selected,o)}>Dodaj wpis</PrimaryAction><SecondaryAction disabled={busy} onClick={()=>void act(()=>data.completeWithoutTransaction(o.id))}>Wykonane bez wpisu</SecondaryAction><SecondaryAction disabled={busy} onClick={()=>selected.plan_type==='fixed_payment'?void act(()=>data.skip(o.id)):setDecision({kind:'skip',occurrence:o})}>Pomiń</SecondaryAction><SecondaryAction disabled={busy} onClick={()=>void act(()=>data.snooze(o.id,new Date(Date.now()+86400000).toISOString()))}>Odłóż o dzień</SecondaryAction>{transactions.filter(t=>!t.is_deleted).slice(0,10).map(t=><button key={t.id} type="button" disabled={busy} onClick={()=>void link(o,t)}>Powiąż: {t.description||t.date}</button>)}</>}</div></article>)}<h4>Historia</h4>{vm.history.length===0?<p>Brak zdarzeń.</p>:vm.history.map(item=><div key={item.id}>{item.created_at}: {item.event_type}</div>)}</section>}
 return <section data-recurring-stage2="list"><div><h3>Płatności cykliczne</h3><PrimaryAction onClick={()=>setDraft(buildRecurringPaymentCreatorViewModel().draft)}>Dodaj plan</PrimaryAction></div>{data.loading?<p>Ładowanie…</p>:cards.length===0?<p>Brak planów.</p>:cards.map(card=><button key={card.id} type="button" data-ui-card="true" onClick={()=>setSelectedId(card.id)}><strong>{card.title}</strong><span>{card.typeLabel} · {card.amountLabel}</span><span>{card.nextDueLabel} · oczekujące: {card.pendingCount} · zaległe: {card.overdueCount}</span></button>)}</section>
}
