'use client'

import { useMemo } from 'react'
import { calculateInstallmentPurchase } from '../../lib/recurring-payments/installments'
import { formatGrosze, parseGrosze } from '../../lib/recurring-payments/money'
import type { InstallmentPurchaseTerms, LoanTerms, RecurringPlanDraft } from '../../lib/recurring-payments/data'
import type { Category, PaymentSource } from '../../lib/budgetPageTypes'
import { PrimaryAction, SecondaryAction } from '../ui/FoundationPrimitives'

type Props={draft:RecurringPlanDraft;setDraft:(draft:RecurringPlanDraft)=>void;categories:Category[];sources:PaymentSource[];busy:boolean;onSave:()=>void;onCancel:()=>void}
const numberValue=(value:string)=>value===''?0:Number(value)
const optionalNumber=(value:string)=>value===''?null:Number(value)

export default function RecurringPaymentPlanForm({draft,setDraft,categories,sources,busy,onSave,onCancel}:Props){
  const installment=draft.installment_terms
  const loan=draft.loan_terms
  const calculation=useMemo(()=>{if(!installment)return null;try{return calculateInstallmentPurchase({purchaseAmountGrosze:parseGrosze(installment.purchase_amount),downPaymentAmountGrosze:parseGrosze(installment.down_payment_amount),installmentCount:installment.declared_installment_count,installmentAmountGrosze:installment.default_installment_amount?parseGrosze(installment.default_installment_amount):null,pricingMode:installment.pricing_mode})}catch{return null}},[installment])
  const changeType=(type:RecurringPlanDraft['plan_type'])=>setDraft({...draft,plan_type:type,installment_terms:type==='installment_purchase'?(installment||{purchase_amount:0,down_payment_amount:0,financed_amount:0,pricing_mode:'zero_percent',declared_installment_count:1,default_installment_amount:0,schedule_mode:'calculated'}):undefined,loan_terms:type==='loan'?(loan||{principal_amount:0,paid_before_tracking_amount:0,installments_paid_before_tracking_count:0,remaining_principal_at_start:null,installment_count:1,initial_installment_amount:0,interest_mode:'unknown',interest_rate:null}):undefined})
  const setInstallment=(patch:Partial<InstallmentPurchaseTerms>)=>{if(!installment)return;const next={...installment,...patch};next.financed_amount=Math.max(next.purchase_amount-next.down_payment_amount,0);setDraft({...draft,amount:next.default_installment_amount||null,installment_terms:next})}
  const setLoan=(patch:Partial<LoanTerms>)=>{if(!loan)return;const next={...loan,...patch};setDraft({...draft,amount:next.initial_installment_amount||null,loan_terms:next})}
  return <section data-recurring-stage2="creator"><h3>{draft.id?'Edytuj plan':'Dodaj plan'}</h3>
    <label>Nazwa<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
    <label>Typ<select value={draft.plan_type} onChange={e=>changeType(e.target.value as RecurringPlanDraft['plan_type'])}><option value="fixed_payment">Stała płatność</option><option value="installment_purchase">Zakup na raty</option><option value="loan">Kredyt / pożyczka</option></select></label>
    <label>Kategoria<select value={draft.category_id} onChange={e=>setDraft({...draft,category_id:e.target.value})}><option value="">Wybierz</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <label>Źródło płatności (opcjonalnie)<select value={draft.payment_source_id||''} onChange={e=>setDraft({...draft,payment_source_id:e.target.value||null})}><option value="">Bez źródła</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
    <label>Opis<input value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value||null})}/></label>
    {draft.plan_type==='fixed_payment'&&<><label>Tryb kwoty<select value={draft.amount_mode} onChange={e=>setDraft({...draft,amount_mode:e.target.value as RecurringPlanDraft['amount_mode'],amount:e.target.value==='reminder_only'?null:draft.amount})}><option value="fixed">Stała</option><option value="variable">Zmienna</option><option value="reminder_only">Tylko przypomnienie</option></select></label>{draft.amount_mode!=='reminder_only'&&<label>Kwota (opcjonalna)<input type="number" min="0" step="0.01" value={draft.amount??''} onChange={e=>setDraft({...draft,amount:optionalNumber(e.target.value)})}/></label>}</>}
    {draft.plan_type==='installment_purchase'&&installment&&<><label>Kwota zakupu<input type="number" min="0" step="0.01" value={installment.purchase_amount} onChange={e=>setInstallment({purchase_amount:numberValue(e.target.value)})}/></label><label>Pierwsza wpłata<input type="number" min="0" step="0.01" value={installment.down_payment_amount} onChange={e=>setInstallment({down_payment_amount:numberValue(e.target.value)})}/></label><label>Kwota finansowana<input readOnly value={installment.financed_amount}/></label><label>Liczba rat<input type="number" min="1" value={installment.declared_installment_count} onChange={e=>setInstallment({declared_installment_count:numberValue(e.target.value)})}/></label><label>Kwota raty<input type="number" min="0" step="0.01" value={installment.default_installment_amount} onChange={e=>setInstallment({default_installment_amount:numberValue(e.target.value)})}/></label><label>Tryb<select value={installment.pricing_mode} onChange={e=>setInstallment({pricing_mode:e.target.value as InstallmentPurchaseTerms['pricing_mode']})}><option value="zero_percent">0%</option><option value="with_cost">Z kosztem</option></select></label>{calculation&&<p>Harmonogram: {calculation.installmentsGrosze.map((value,index)=>`${index+1}: ${formatGrosze(value)}`).join(', ')}. Rata wyrównawcza: {formatGrosze(calculation.installmentsGrosze.at(-1)!)}</p>}</>}
    {draft.plan_type==='loan'&&loan&&<><label>Kapitał początkowy<input type="number" min="0" step="0.01" value={loan.principal_amount} onChange={e=>setLoan({principal_amount:numberValue(e.target.value)})}/></label><label>Zapłacone przed BudżAppką<input type="number" min="0" step="0.01" value={loan.paid_before_tracking_amount} onChange={e=>setLoan({paid_before_tracking_amount:numberValue(e.target.value)})}/></label><label>Raty zapłacone wcześniej<input type="number" min="0" value={loan.installments_paid_before_tracking_count} onChange={e=>setLoan({installments_paid_before_tracking_count:numberValue(e.target.value)})}/></label><label>Pozostały kapitał (opcjonalnie)<input type="number" min="0" step="0.01" value={loan.remaining_principal_at_start??''} onChange={e=>setLoan({remaining_principal_at_start:optionalNumber(e.target.value)})}/></label><label>Liczba rat<input type="number" min="1" value={loan.installment_count} onChange={e=>setLoan({installment_count:numberValue(e.target.value)})}/></label><label>Rata startowa<input type="number" min="0" step="0.01" value={loan.initial_installment_amount} onChange={e=>setLoan({initial_installment_amount:numberValue(e.target.value)})}/></label><label>Tryb oprocentowania<select value={loan.interest_mode} onChange={e=>setLoan({interest_mode:e.target.value as LoanTerms['interest_mode']})}><option value="fixed">Stałe</option><option value="variable">Zmienne</option><option value="unknown">Nieznane</option></select></label><label>Oprocentowanie informacyjne (%)<input type="number" min="0" step="0.01" value={loan.interest_rate??''} onChange={e=>setLoan({interest_rate:optionalNumber(e.target.value)})}/></label></>}
    <label>Interwał<select value={draft.cadence_unit} onChange={e=>setDraft({...draft,cadence_unit:e.target.value as RecurringPlanDraft['cadence_unit']})}><option value="day">Dni</option><option value="week">Tygodnie</option><option value="month">Miesiące</option><option value="year">Lata</option></select><input type="number" min="1" value={draft.cadence_interval} onChange={e=>setDraft({...draft,cadence_interval:Math.max(numberValue(e.target.value),1)})}/></label>
    <label>{draft.plan_type==='fixed_payment'?'Data startu / pierwszy termin przypomnienia':'Data pierwszej raty'}<input type="date" value={draft.start_date||''} onChange={e=>setDraft({...draft,start_date:e.target.value})}/></label>
    <div><PrimaryAction disabled={busy||!draft.name.trim()||!draft.category_id} onClick={onSave}>{draft.id?'Zapisz zmiany':'Dodaj plan'}</PrimaryAction><SecondaryAction onClick={onCancel}>Anuluj</SecondaryAction></div>
  </section>
}
