'use client'
import { useMemo, useState } from 'react'
import type { Category, PaymentSource, Transaction } from '../../lib/budgetPageTypes'
import type { RecurringPlanDraft } from '../../lib/recurring-payments/data'
import { useRecurringPaymentsData } from '../../lib/recurring-payments/useRecurringPaymentsData'
import { buildRecurringPaymentCardViewModel, buildRecurringPaymentCreatorViewModel, buildRecurringPaymentDetailsViewModel } from '../../lib/recurring-payments/viewModels'
import { PrimaryAction, SecondaryAction } from '../ui/FoundationPrimitives'

type Props={profileId:string;categoriesById:Record<string,Category>;categoryOptions:Category[];paymentSources:PaymentSource[];transactions:Transaction[]}
export default function RecurringPaymentsStage2Panel({profileId,categoriesById,categoryOptions,paymentSources,transactions}:Props){
 const data=useRecurringPaymentsData(profileId);const [selectedId,setSelectedId]=useState<string|null>(null);const [draft,setDraft]=useState<RecurringPlanDraft|null>(null);const [busy,setBusy]=useState(false);const today=new Date().toISOString().slice(0,10)
 const selected=data.plans.find(p=>p.id===selectedId)||null;const selectedOccurrences=data.occurrences.filter(o=>o.plan_id===selectedId)
 const cards=useMemo(()=>data.plans.map(p=>buildRecurringPaymentCardViewModel(p,data.occurrences.filter(o=>o.plan_id===p.id),today)),[data.plans,data.occurrences,today])
 const save=async()=>{if(!draft||!draft.name.trim()||!draft.category_id)return;setBusy(true);try{await (draft.id?data.updatePlan(draft):data.createPlan(draft));setDraft(null)}finally{setBusy(false)}}
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}finally{setBusy(false)}}
 if(data.error)return <div data-ui-empty-state="true">Etap 2 wymaga zastosowania migracji <code>recurring_payments_stage_2.sql</code>. {data.error}</div>
 if(draft){const creator=buildRecurringPaymentCreatorViewModel(data.plans.find(p=>p.id===draft.id));return <section data-recurring-stage2="creator"><h3>{creator.title}</h3><label>Nazwa<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Typ<select value={draft.plan_type} onChange={e=>setDraft({...draft,plan_type:e.target.value as RecurringPlanDraft['plan_type']})}><option value="fixed_payment">Stała płatność</option><option value="installment_purchase">Zakup na raty</option><option value="loan">Kredyt / pożyczka</option></select></label><label>Kategoria<select value={draft.category_id} onChange={e=>setDraft({...draft,category_id:e.target.value})}><option value="">Wybierz</option>{categoryOptions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Kwota<input type="number" min="0" step="0.01" value={draft.amount??''} onChange={e=>setDraft({...draft,amount:e.target.value===''?null:Number(e.target.value)})}/></label><label>Data startu<input type="date" value={draft.start_date||''} onChange={e=>setDraft({...draft,start_date:e.target.value})}/></label><div><PrimaryAction disabled={busy||!draft.name.trim()||!draft.category_id} onClick={()=>void save()}>{creator.submitLabel}</PrimaryAction><SecondaryAction onClick={()=>setDraft(null)}>Anuluj</SecondaryAction></div></section>}
 if(selected){const vm=buildRecurringPaymentDetailsViewModel(selected,selectedOccurrences,categoriesById,paymentSources,today);return <section data-recurring-stage2="details"><SecondaryAction onClick={()=>setSelectedId(null)}>Wróć do listy</SecondaryAction><h3>{vm.title}</h3><p>{vm.typeLabel} · {vm.categoryLabel} · {vm.paymentSourceLabel}</p><PrimaryAction onClick={()=>setDraft({...selected})}>Edytuj</PrimaryAction><h4>Wystąpienia</h4>{vm.occurrences.length===0?<p>Brak wygenerowanych wystąpień.</p>:vm.occurrences.map(o=><article key={o.id} data-ui-card="true"><strong>{o.due_date}</strong> · {o.amountLabel} · {o.stateLabel}<div>{o.status==='pending'&&<><SecondaryAction disabled={busy} onClick={()=>void act(()=>data.completeWithoutTransaction(o.id))}>Wykonane bez wpisu</SecondaryAction><SecondaryAction disabled={busy} onClick={()=>void act(()=>data.skip(o.id))}>Pomiń</SecondaryAction><SecondaryAction disabled={busy} onClick={()=>void act(()=>data.snooze(o.id,new Date(Date.now()+86400000).toISOString()))}>Odłóż o dzień</SecondaryAction>{transactions.filter(t=>!t.is_deleted).slice(0,10).map(t=><button key={t.id} type="button" disabled={busy} onClick={()=>void act(()=>data.linkTransaction(o.id,t.id))}>Powiąż: {t.description||t.date}</button>)}</>}</div></article>)}</section>}
 return <section data-recurring-stage2="list"><div><h3>Płatności cykliczne</h3><PrimaryAction onClick={()=>setDraft(buildRecurringPaymentCreatorViewModel().draft)}>Dodaj plan</PrimaryAction></div>{data.loading?<p>Ładowanie…</p>:cards.length===0?<p>Brak planów.</p>:cards.map(card=><button key={card.id} type="button" data-ui-card="true" onClick={()=>setSelectedId(card.id)}><strong>{card.title}</strong><span>{card.typeLabel} · {card.amountLabel}</span><span>{card.nextDueLabel} · oczekujące: {card.pendingCount}</span></button>)}</section>
}
